TO DO:

- Sift through tables of interest for FIA

COMPLETED:

In [34]:
import pandas as pd
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt
%matplotlib inline

In [35]:
# importing tn counties shape
tn_counties = gpd.read_file('../data/county/tncounty.shp')

In [39]:
# creating dictionaries for all years

# create a dicitonary (with sheet_name =['<sheet1>', '<sheet2>', '<sheet3>'])
# use .get('<sheetname>') to parse into separate dfs

dict_trees2016 = pd.read_excel('../data/TN_2016.xlsx',
                               sheet_name = ['Tab 2', 'Tab 8', 'Tab 12', 'Tab 24', 'Tab 32'])
dict_trees2015 = pd.read_excel('../data/TN_2015.xls',
                               sheet_name = ['Tab 2', 'Tab 8', 'Tab 12', 'Tab 24', 'Tab 32'])
dict_trees2014 = pd.read_excel('../data/TN_2014.xls',
                               sheet_name = ['Tab 2', 'Tab 8', 'Tab 12', 'Tab 24', 'Tab 32'])
dict_trees2013 = pd.read_excel('../data/TN_2013.xls',
                               sheet_name = ['Tab 2', 'Tab 8', 'Tab 12', 'Tab 24', 'Tab 32'])
dict_trees2012 = pd.read_excel('../data/TN_2012.xls',
                               sheet_name = ['Tab 2', 'Tab 8', 'Tab 12', 'Tab 24', 'Tab 32'])
dict_trees2011 = pd.read_excel('../data/TN_2011.xls',
                               sheet_name = ['Tab 2', 'Tab 8', 'Tab 12', 'Tab 24', 'Tab 32'])
dict_trees2010 = pd.read_excel('../data/TN_2010.xls',
                               sheet_name = ['Tab 2', 'Tab 8', 'Tab 12', 'Tab 24', 'Tab 32'])
dict_trees2009 = pd.read_excel('../data/TN_2009.xls',
                               sheet_name = ['Tab 2', 'Tab 8', 'Tab 12', 'Tab 24', 'Tab 32'])
dict_trees2008 = pd.read_excel('../data/TN_2008.xls',
                               sheet_name = ['Tab 2', 'Tab 8', 'Tab 12', 'Tab 24', 'Tab 32'])
dict_trees2007 = pd.read_excel('../data/TN_2007.xls',
                               sheet_name = ['Tab 2', 'Tab 8', 'Tab 12', 'Tab 24', 'Tab 32'])

In [86]:
## Table 2
## Land by Ownership Class, in thousand acres

# 2016
ownership_class_2016 = dict_trees2016.get('Tab 2')
ownership_class_2016.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
ownership_class_2016 = ownership_class_2016.head(28)
ownership_class_2016 = ownership_class_2016.tail(25)
ownership_class_2016 = ownership_class_2016.reset_index(drop=True)
ownership_class_2016 = ownership_class_2016[['class_type', 'all_forest_land']]

ownership_class_2016.at[3, 'class_type']='us_forest_service'
ownership_class_2016.at[9, 'class_type']='other_federal'
ownership_class_2016.at[13, 'class_type']='state_and_local_gov'
ownership_class_2016.at[17, 'class_type']='forest_industry'
ownership_class_2016.at[23, 'class_type']='nonindustrial_private'
ownership_class_2016.at[24, 'class_type']='total_land'
ownership_class_2016 = ownership_class_2016.set_index('class_type')
ownership_class_2016 = ownership_class_2016.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'forest_industry', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
ownership_class_2016['year'] = '2016'

#######

# 2015
ownership_class_2015 = dict_trees2015.get('Tab 2')
ownership_class_2015.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
ownership_class_2015 = ownership_class_2015.head(21)
ownership_class_2015 = ownership_class_2015.tail(18)
ownership_class_2015 = ownership_class_2015.reset_index(drop=True)
ownership_class_2015 = ownership_class_2015[['class_type', 'all_forest_land']]

ownership_class_2015.at[3, 'class_type']='us_forest_service'
ownership_class_2015.at[9, 'class_type']='other_federal'
ownership_class_2015.at[13, 'class_type']='state_and_local_gov'
ownership_class_2015.at[16, 'class_type']='nonindustrial_private'
ownership_class_2015.at[17, 'class_type']='total_land'
ownership_class_2015 = ownership_class_2015.set_index('class_type')
ownership_class_2015 = ownership_class_2015.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
ownership_class_2015['year'] = '2015'

######

# 2014
ownership_class_2014 = dict_trees2014.get('Tab 2')
ownership_class_2014.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
ownership_class_2014 = ownership_class_2014.head(21)
ownership_class_2014 = ownership_class_2014.tail(18)
ownership_class_2014 = ownership_class_2014.reset_index(drop=True)
ownership_class_2014 = ownership_class_2014[['class_type', 'all_forest_land']]

ownership_class_2014.at[3, 'class_type']='us_forest_service'
ownership_class_2014.at[9, 'class_type']='other_federal'
ownership_class_2014.at[13, 'class_type']='state_and_local_gov'
ownership_class_2014.at[16, 'class_type']='nonindustrial_private'
ownership_class_2014.at[17, 'class_type']='total_land'
ownership_class_2014 = ownership_class_2014.set_index('class_type')
ownership_class_2014 = ownership_class_2014.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
ownership_class_2014['year'] = '2014'

######

# 2013
ownership_class_2013 = dict_trees2013.get('Tab 2')
ownership_class_2013.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
ownership_class_2013 = ownership_class_2013.head(21)
ownership_class_2013 = ownership_class_2013.tail(18)
ownership_class_2013 = ownership_class_2013.reset_index(drop=True)
ownership_class_2013 = ownership_class_2013[['class_type', 'all_forest_land']]

ownership_class_2013.at[3, 'class_type']='us_forest_service'
ownership_class_2013.at[9, 'class_type']='other_federal'
ownership_class_2013.at[13, 'class_type']='state_and_local_gov'
ownership_class_2013.at[16, 'class_type']='nonindustrial_private'
ownership_class_2013.at[17, 'class_type']='total_land'
ownership_class_2013 = ownership_class_2013.set_index('class_type')
ownership_class_2013 = ownership_class_2013.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
ownership_class_2013['year'] = '2013'

######

#2012
ownership_class_2012 = dict_trees2012.get('Tab 2')
ownership_class_2012.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
ownership_class_2012 = ownership_class_2012.head(21)
ownership_class_2012 = ownership_class_2012.tail(18)
ownership_class_2012 = ownership_class_2012.reset_index(drop=True)
ownership_class_2012 = ownership_class_2012[['class_type', 'all_forest_land']]

ownership_class_2012.at[3, 'class_type']='us_forest_service'
ownership_class_2012.at[9, 'class_type']='other_federal'
ownership_class_2012.at[13, 'class_type']='state_and_local_gov'
ownership_class_2012.at[16, 'class_type']='nonindustrial_private'
ownership_class_2012.at[17, 'class_type']='total_land'
ownership_class_2012 = ownership_class_2012.set_index('class_type')
ownership_class_2012 = ownership_class_2012.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
ownership_class_2012['year'] = '2012'

######

# 2011
ownership_class_2011 = dict_trees2011.get('Tab 2')
ownership_class_2011.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
ownership_class_2011 = ownership_class_2011.head(21)
ownership_class_2011 = ownership_class_2011.tail(18)
ownership_class_2011 = ownership_class_2011.reset_index(drop=True)
ownership_class_2011 = ownership_class_2011[['class_type', 'all_forest_land']]

ownership_class_2011.at[3, 'class_type']='us_forest_service'
ownership_class_2011.at[9, 'class_type']='other_federal'
ownership_class_2011.at[13, 'class_type']='state_and_local_gov'
ownership_class_2011.at[16, 'class_type']='nonindustrial_private'
ownership_class_2011.at[17, 'class_type']='total_land'
ownership_class_2011 = ownership_class_2011.set_index('class_type')
ownership_class_2011 = ownership_class_2011.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
ownership_class_2011['year'] = '2011'

######

# 2010
ownership_class_2010 = dict_trees2010.get('Tab 2')
ownership_class_2010.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
ownership_class_2010 = ownership_class_2010.head(21)
ownership_class_2010 = ownership_class_2010.tail(18)
ownership_class_2010 = ownership_class_2010.reset_index(drop=True)
ownership_class_2010 = ownership_class_2010[['class_type', 'all_forest_land']]

ownership_class_2010.at[3, 'class_type']='us_forest_service'
ownership_class_2010.at[9, 'class_type']='other_federal'
ownership_class_2010.at[13, 'class_type']='state_and_local_gov'
ownership_class_2010.at[16, 'class_type']='nonindustrial_private'
ownership_class_2010.at[17, 'class_type']='total_land'
ownership_class_2010 = ownership_class_2010.set_index('class_type')
ownership_class_2010 = ownership_class_2010.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
ownership_class_2010['year'] = '2010'

######

# 2009
ownership_class_2009 = dict_trees2009.get('Tab 2')
ownership_class_2009.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
ownership_class_2009 = ownership_class_2009.head(21)
ownership_class_2009 = ownership_class_2009.tail(18)
ownership_class_2009 = ownership_class_2009.reset_index(drop=True)
ownership_class_2009 = ownership_class_2009[['class_type', 'all_forest_land']]

ownership_class_2009.at[3, 'class_type']='us_forest_service'
ownership_class_2009.at[9, 'class_type']='other_federal'
ownership_class_2009.at[13, 'class_type']='state_and_local_gov'
ownership_class_2009.at[16, 'class_type']='nonindustrial_private'
ownership_class_2009.at[17, 'class_type']='total_land'
ownership_class_2009 = ownership_class_2009.set_index('class_type')
ownership_class_2009 = ownership_class_2009.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
ownership_class_2009['year'] = '2009'

######

# 2008
ownership_class_2008 = dict_trees2008.get('Tab 2')
ownership_class_2008.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
ownership_class_2008 = ownership_class_2008.head(21)
ownership_class_2008 = ownership_class_2008.tail(18)
ownership_class_2008 = ownership_class_2008.reset_index(drop=True)
ownership_class_2008 = ownership_class_2008[['class_type', 'all_forest_land']]

ownership_class_2008.at[3, 'class_type']='us_forest_service'
ownership_class_2008.at[9, 'class_type']='other_federal'
ownership_class_2008.at[13, 'class_type']='state_and_local_gov'
ownership_class_2008.at[16, 'class_type']='nonindustrial_private'
ownership_class_2008.at[17, 'class_type']='total_land'
ownership_class_2008 = ownership_class_2008.set_index('class_type')
ownership_class_2008 = ownership_class_2008.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
ownership_class_2008['year'] = '2008'

######

# 2007
ownership_class_2007 = dict_trees2007.get('Tab 2')
ownership_class_2007.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
ownership_class_2007 = ownership_class_2007.head(22)
ownership_class_2007 = ownership_class_2007.tail(19)
ownership_class_2007 = ownership_class_2007.reset_index(drop=True)
ownership_class_2007 = ownership_class_2007[['class_type', 'all_forest_land']]

ownership_class_2007.at[3, 'class_type']='us_forest_service'
ownership_class_2007.at[9, 'class_type']='other_federal'
ownership_class_2007.at[14, 'class_type']='state_and_local_gov'
ownership_class_2007.at[17, 'class_type']='nonindustrial_private'
ownership_class_2007.at[18, 'class_type']='total_land'
ownership_class_2007 = ownership_class_2007.set_index('class_type')
ownership_class_2007 = ownership_class_2007.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
ownership_class_2007['year'] = '2007'

# combining all tables
ownership_class = pd.concat([ownership_class_2007, ownership_class_2008, ownership_class_2009, ownership_class_2010, ownership_class_2011, ownership_class_2012, ownership_class_2013, ownership_class_2014, ownership_class_2015, ownership_class_2016])
ownership_class = ownership_class.reset_index(drop=True)
ownership_class = ownership_class[['year', 'us_forest_service', 'other_federal', 'state_and_local_gov', 'forest_industry', 'nonindustrial_private', 'total_land']]
ownership_class

class_type,year,us_forest_service,other_federal,state_and_local_gov,forest_industry,nonindustrial_private,total_land
0,2007,717.1,663.5,792.4,NaN,11817.3,13990.4
1,2008,722.1,659.4,809.4,NaN,11788.3,13979.1
2,2009,715.9,659.6,823.4,NaN,11805.1,14004.1
3,2010,724.6,661.5,840.7,NaN,11730,13956.7
4,2011,723.8,675.8,869.2,NaN,11672.4,13941.3
5,2012,717.3,684.9,854.1,NaN,11664.1,13920.5
6,2013,723.3,683.1,914.4,NaN,11646.3,13967.1
7,2014,719.9,673.2,902,NaN,11585.3,13880.3
8,2015,713.7,671.8,920.2,NaN,11593.9,13899.5
9,2016,712.8,671.6,935.3,120.4,11479.4,13919.5

In [87]:
ownership_class.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   year                   10 non-null     object
 1   us_forest_service      10 non-null     object
 2   other_federal          10 non-null     object
 3   state_and_local_gov    10 non-null     object
 4   forest_industry        1 non-null      object
 5   nonindustrial_private  10 non-null     object
 6   total_land             10 non-null     object
dtypes: object(7)
memory usage: 688.0+ bytes

In [4]:
disturbed_2016 = dict_trees2016.get('Tab 8')
disturbed_2016.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
land_by_ownership_class = land_by_ownership_class.head(28)
land_by_ownership_class = land_by_ownership_class.tail(25)
land_by_ownership_class = land_by_ownership_class.set_index('class_type')

,"CHNG Table 8—Area of forest land disturbed annually by forest-type group and disturbance class, Tennessee, 2016",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Disturbance classa ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Forest-type groupb,Insects,Disease,Weather,Fire,Domestic animals,Wild animals,Human,Other natural
2,thousand acres ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Softwood types,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,White-red-jack pine,0.9,0,0,0,0,0,0,0
5,Spruce-fir,0,0,0,0,0,0,0,0
6,Loblolly-shortleaf pine,0,0,0.5,5.3,3.9,0,1.5,0
7,Other eastern softwoods,0,0,0,0,6.1,0,0,0
8,Total softwoods,0.9,0,0.5,5.3,9.9,0,1.5,0
9,Hardwood types,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Oak-pine,2.8,0.4,2.2,2.7,7,0.8,2.5,0.2
11,Oak-hickory,14.9,4,13.1,17,32.8,2.4,6,2.2
12,Oak-gum-cypress,0,0,5.5,0,0.2,0,0,0
13,Elm-ash-cottonwood,0.7,0,6.5,0.6,2.1,1.9,1,1.6
14,Maple-beech-birch,3.4,0,0.7,0,1.8,0,0,0.1
15,Other hardwoods,1.3,0,0,0,0,0,0,0
16,Exotic hardwoods,0,0,0,0,1.2,0,0,0
17,Total hardwoods,23.2,4.4,27.9,20.3,45.2,5.1,9.5,4
18,Nonstocked,0,0,0,0.2,0,0,0.7,0
19,All groups,24.1,4.4,28.5,25.8,55.2,5.1,11.7,4
20,Numbers in rows and columns may not sum to tot...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Table created:26-MAR-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,0.0 = no sample for the cell or a value of >0....,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,aBased on current conditions.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,bBased on past conditions.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN