TO DO:
- add % columns in each table

COMPLETED:
- compile ownership class table
- compile disturbed table
- compile volume table
- compile growth table
- compile removals table

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# creating dictionaries for all years

# create a dicitonary (with sheet_name =['<sheet1>', '<sheet2>', '<sheet3>'])
# use .get('<sheetname>') to parse into separate dfs

dict_trees2016 = pd.read_excel('../data/TN_2016.xlsx',
                               sheet_name = ['Tab 2', 'Tab 8', 'Tab 10', 'Tab 12', 'Tab 24', 'Tab 32'])
dict_trees2015 = pd.read_excel('../data/TN_2015.xls',
                               sheet_name = ['Tab 2', 'Tab 8', 'Tab 10', 'Tab 12', 'Tab 24', 'Tab 32'])
dict_trees2014 = pd.read_excel('../data/TN_2014.xls',
                               sheet_name = ['Tab 2', 'Tab 8', 'Tab 10', 'Tab 12', 'Tab 24', 'Tab 32'])
dict_trees2013 = pd.read_excel('../data/TN_2013.xls',
                               sheet_name = ['Tab 2', 'Tab 8', 'Tab 10', 'Tab 12', 'Tab 24', 'Tab 32'])
dict_trees2012 = pd.read_excel('../data/TN_2012.xls',
                               sheet_name = ['Tab 2', 'Tab 8', 'Tab 10', 'Tab 12', 'Tab 24', 'Tab 32'])
dict_trees2011 = pd.read_excel('../data/TN_2011.xls',
                               sheet_name = ['Tab 2', 'Tab 8', 'Tab 10', 'Tab 12', 'Tab 24', 'Tab 32'])
dict_trees2010 = pd.read_excel('../data/TN_2010.xls',
                               sheet_name = ['Tab 2', 'Tab 8', 'Tab 10', 'Tab 12', 'Tab 24', 'Tab 32'])
dict_trees2009 = pd.read_excel('../data/TN_2009.xls',
                               sheet_name = ['Tab 2', 'Tab 8', 'Tab 10', 'Tab 12', 'Tab 24', 'Tab 32'])
dict_trees2008 = pd.read_excel('../data/TN_2008.xls',
                               sheet_name = ['Tab 2', 'Tab 8', 'Tab 10', 'Tab 12', 'Tab 24', 'Tab 32'])
dict_trees2007 = pd.read_excel('../data/TN_2007.xls',
                               sheet_name = ['Tab 2', 'Tab 8', 'Tab 10', 'Tab 12', 'Tab 24', 'Tab 32'])

In [3]:
## Table 2
## Land by Ownership Class, in thousand acres

# 2016
ownership_class_2016 = dict_trees2016.get('Tab 2')
ownership_class_2016.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
ownership_class_2016 = ownership_class_2016.head(28)
ownership_class_2016 = ownership_class_2016.tail(25)
ownership_class_2016 = ownership_class_2016.reset_index(drop=True)
ownership_class_2016 = ownership_class_2016[['class_type', 'all_forest_land']]

ownership_class_2016.at[3, 'class_type']='us_forest_service'
ownership_class_2016.at[9, 'class_type']='other_federal'
ownership_class_2016.at[13, 'class_type']='state_and_local_gov'
ownership_class_2016.at[17, 'class_type']='forest_industry'
ownership_class_2016.at[23, 'class_type']='nonindustrial_private'
ownership_class_2016.at[24, 'class_type']='total_land'
ownership_class_2016 = ownership_class_2016.set_index('class_type')
ownership_class_2016 = ownership_class_2016.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'forest_industry', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
ownership_class_2016['year'] = '2016'

#######

# 2015
ownership_class_2015 = dict_trees2015.get('Tab 2')
ownership_class_2015.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
ownership_class_2015 = ownership_class_2015.head(21)
ownership_class_2015 = ownership_class_2015.tail(18)
ownership_class_2015 = ownership_class_2015.reset_index(drop=True)
ownership_class_2015 = ownership_class_2015[['class_type', 'all_forest_land']]

ownership_class_2015.at[3, 'class_type']='us_forest_service'
ownership_class_2015.at[9, 'class_type']='other_federal'
ownership_class_2015.at[13, 'class_type']='state_and_local_gov'
ownership_class_2015.at[16, 'class_type']='nonindustrial_private'
ownership_class_2015.at[17, 'class_type']='total_land'
ownership_class_2015 = ownership_class_2015.set_index('class_type')
ownership_class_2015 = ownership_class_2015.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
ownership_class_2015['year'] = '2015'

######

# 2014
ownership_class_2014 = dict_trees2014.get('Tab 2')
ownership_class_2014.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
ownership_class_2014 = ownership_class_2014.head(21)
ownership_class_2014 = ownership_class_2014.tail(18)
ownership_class_2014 = ownership_class_2014.reset_index(drop=True)
ownership_class_2014 = ownership_class_2014[['class_type', 'all_forest_land']]

ownership_class_2014.at[3, 'class_type']='us_forest_service'
ownership_class_2014.at[9, 'class_type']='other_federal'
ownership_class_2014.at[13, 'class_type']='state_and_local_gov'
ownership_class_2014.at[16, 'class_type']='nonindustrial_private'
ownership_class_2014.at[17, 'class_type']='total_land'
ownership_class_2014 = ownership_class_2014.set_index('class_type')
ownership_class_2014 = ownership_class_2014.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
ownership_class_2014['year'] = '2014'

######

# 2013
ownership_class_2013 = dict_trees2013.get('Tab 2')
ownership_class_2013.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
ownership_class_2013 = ownership_class_2013.head(21)
ownership_class_2013 = ownership_class_2013.tail(18)
ownership_class_2013 = ownership_class_2013.reset_index(drop=True)
ownership_class_2013 = ownership_class_2013[['class_type', 'all_forest_land']]

ownership_class_2013.at[3, 'class_type']='us_forest_service'
ownership_class_2013.at[9, 'class_type']='other_federal'
ownership_class_2013.at[13, 'class_type']='state_and_local_gov'
ownership_class_2013.at[16, 'class_type']='nonindustrial_private'
ownership_class_2013.at[17, 'class_type']='total_land'
ownership_class_2013 = ownership_class_2013.set_index('class_type')
ownership_class_2013 = ownership_class_2013.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
ownership_class_2013['year'] = '2013'

######

#2012
ownership_class_2012 = dict_trees2012.get('Tab 2')
ownership_class_2012.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
ownership_class_2012 = ownership_class_2012.head(21)
ownership_class_2012 = ownership_class_2012.tail(18)
ownership_class_2012 = ownership_class_2012.reset_index(drop=True)
ownership_class_2012 = ownership_class_2012[['class_type', 'all_forest_land']]

ownership_class_2012.at[3, 'class_type']='us_forest_service'
ownership_class_2012.at[9, 'class_type']='other_federal'
ownership_class_2012.at[13, 'class_type']='state_and_local_gov'
ownership_class_2012.at[16, 'class_type']='nonindustrial_private'
ownership_class_2012.at[17, 'class_type']='total_land'
ownership_class_2012 = ownership_class_2012.set_index('class_type')
ownership_class_2012 = ownership_class_2012.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
ownership_class_2012['year'] = '2012'

######

# 2011
ownership_class_2011 = dict_trees2011.get('Tab 2')
ownership_class_2011.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
ownership_class_2011 = ownership_class_2011.head(21)
ownership_class_2011 = ownership_class_2011.tail(18)
ownership_class_2011 = ownership_class_2011.reset_index(drop=True)
ownership_class_2011 = ownership_class_2011[['class_type', 'all_forest_land']]

ownership_class_2011.at[3, 'class_type']='us_forest_service'
ownership_class_2011.at[9, 'class_type']='other_federal'
ownership_class_2011.at[13, 'class_type']='state_and_local_gov'
ownership_class_2011.at[16, 'class_type']='nonindustrial_private'
ownership_class_2011.at[17, 'class_type']='total_land'
ownership_class_2011 = ownership_class_2011.set_index('class_type')
ownership_class_2011 = ownership_class_2011.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
ownership_class_2011['year'] = '2011'

######

# 2010
ownership_class_2010 = dict_trees2010.get('Tab 2')
ownership_class_2010.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
ownership_class_2010 = ownership_class_2010.head(21)
ownership_class_2010 = ownership_class_2010.tail(18)
ownership_class_2010 = ownership_class_2010.reset_index(drop=True)
ownership_class_2010 = ownership_class_2010[['class_type', 'all_forest_land']]

ownership_class_2010.at[3, 'class_type']='us_forest_service'
ownership_class_2010.at[9, 'class_type']='other_federal'
ownership_class_2010.at[13, 'class_type']='state_and_local_gov'
ownership_class_2010.at[16, 'class_type']='nonindustrial_private'
ownership_class_2010.at[17, 'class_type']='total_land'
ownership_class_2010 = ownership_class_2010.set_index('class_type')
ownership_class_2010 = ownership_class_2010.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
ownership_class_2010['year'] = '2010'

######

# 2009
ownership_class_2009 = dict_trees2009.get('Tab 2')
ownership_class_2009.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
ownership_class_2009 = ownership_class_2009.head(21)
ownership_class_2009 = ownership_class_2009.tail(18)
ownership_class_2009 = ownership_class_2009.reset_index(drop=True)
ownership_class_2009 = ownership_class_2009[['class_type', 'all_forest_land']]

ownership_class_2009.at[3, 'class_type']='us_forest_service'
ownership_class_2009.at[9, 'class_type']='other_federal'
ownership_class_2009.at[13, 'class_type']='state_and_local_gov'
ownership_class_2009.at[16, 'class_type']='nonindustrial_private'
ownership_class_2009.at[17, 'class_type']='total_land'
ownership_class_2009 = ownership_class_2009.set_index('class_type')
ownership_class_2009 = ownership_class_2009.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
ownership_class_2009['year'] = '2009'

######

# 2008
ownership_class_2008 = dict_trees2008.get('Tab 2')
ownership_class_2008.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
ownership_class_2008 = ownership_class_2008.head(21)
ownership_class_2008 = ownership_class_2008.tail(18)
ownership_class_2008 = ownership_class_2008.reset_index(drop=True)
ownership_class_2008 = ownership_class_2008[['class_type', 'all_forest_land']]

ownership_class_2008.at[3, 'class_type']='us_forest_service'
ownership_class_2008.at[9, 'class_type']='other_federal'
ownership_class_2008.at[13, 'class_type']='state_and_local_gov'
ownership_class_2008.at[16, 'class_type']='nonindustrial_private'
ownership_class_2008.at[17, 'class_type']='total_land'
ownership_class_2008 = ownership_class_2008.set_index('class_type')
ownership_class_2008 = ownership_class_2008.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
ownership_class_2008['year'] = '2008'

######

# 2007
ownership_class_2007 = dict_trees2007.get('Tab 2')
ownership_class_2007.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
ownership_class_2007 = ownership_class_2007.head(22)
ownership_class_2007 = ownership_class_2007.tail(19)
ownership_class_2007 = ownership_class_2007.reset_index(drop=True)
ownership_class_2007 = ownership_class_2007[['class_type', 'all_forest_land']]

ownership_class_2007.at[3, 'class_type']='us_forest_service'
ownership_class_2007.at[9, 'class_type']='other_federal'
ownership_class_2007.at[14, 'class_type']='state_and_local_gov'
ownership_class_2007.at[17, 'class_type']='nonindustrial_private'
ownership_class_2007.at[18, 'class_type']='total_land'
ownership_class_2007 = ownership_class_2007.set_index('class_type')
ownership_class_2007 = ownership_class_2007.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
ownership_class_2007['year'] = '2007'

# combining all tables
ownership_class = pd.concat([ownership_class_2007, ownership_class_2008, ownership_class_2009, ownership_class_2010, ownership_class_2011, ownership_class_2012, ownership_class_2013, ownership_class_2014, ownership_class_2015, ownership_class_2016])
ownership_class = ownership_class.reset_index(drop=True)
ownership_class = ownership_class[['year', 'us_forest_service', 'other_federal', 'state_and_local_gov', 'forest_industry', 'nonindustrial_private', 'total_land']]

# changing data type to numeric
ownership_class.us_forest_service = pd.to_numeric(ownership_class.us_forest_service)
ownership_class.other_federal = pd.to_numeric(ownership_class.other_federal)
ownership_class.state_and_local_gov = pd.to_numeric(ownership_class.state_and_local_gov)
ownership_class.forest_industry = pd.to_numeric(ownership_class.forest_industry)
ownership_class.nonindustrial_private = pd.to_numeric(ownership_class.nonindustrial_private)
ownership_class.total_land = pd.to_numeric(ownership_class.total_land)

# adding perc columns
ownership_class['perc_us_forest_service'] = round(ownership_class.us_forest_service/ownership_class.total_land*100,2)
ownership_class['perc_other_federal'] = round(ownership_class.other_federal/ownership_class.total_land*100,2)
ownership_class['perc_state_and_local_gov'] = round(ownership_class.state_and_local_gov/ownership_class.total_land*100,2)
ownership_class['perc_forest_industry'] = round(ownership_class.forest_industry/ownership_class.total_land*100,2)
ownership_class['perc_nonindustrial_private'] = round(ownership_class.nonindustrial_private/ownership_class.total_land*100,2)

# fixing format
ownership_class_sub = pd.melt(ownership_class, id_vars='year', value_vars=['us_forest_service', 'other_federal', 'state_and_local_gov', 'forest_industry', 'nonindustrial_private'])
ownership_class_sub.columns = ['year', 'class_type', 'thousand_acres']
ownership_class_perc = ownership_class.drop(columns=['us_forest_service', 'other_federal', 'state_and_local_gov', 'forest_industry', 'nonindustrial_private', 'total_land'])
ownership_class_perc.columns = ['year', 'us_forest_service', 'other_federal', 'state_and_local_gov', 'forest_industry', 'nonindustrial_private']
ownership_class_perc = pd.melt(ownership_class_perc, id_vars='year', value_vars=['us_forest_service', 'other_federal', 'state_and_local_gov', 'forest_industry', 'nonindustrial_private'])
ownership_class_perc.columns = ['year', 'class_type', 'perc_total_land']
ownership_class = pd.merge(ownership_class_sub, ownership_class_perc, on=['year', 'class_type'], how='inner')

In [4]:
## Table 8
## Land by Disturbance Type, in thousand acres

# 2016
disturbed_2016 = dict_trees2016.get('Tab 8')
disturbed_2016.columns = ['drop', 'insects', 'disease', 'weather', 'fire', 'domestic_animals', 'wild_animals', 'humans', 'other_natural']
disturbed_2016 = disturbed_2016[['insects', 'disease', 'weather', 'fire', 'domestic_animals', 'wild_animals', 'humans', 'other_natural']]
disturbed_2016 = disturbed_2016.head(20)
disturbed_2016 = disturbed_2016.tail(1)
disturbed_2016['year'] = '2016'

######

# 2015
disturbed_2015 = dict_trees2015.get('Tab 8')
disturbed_2015.columns = ['drop', 'insects', 'disease', 'weather', 'fire', 'domestic_animals', 'wild_animals', 'humans', 'other_natural']
disturbed_2015 = disturbed_2015[['insects', 'disease', 'weather', 'fire', 'domestic_animals', 'wild_animals', 'humans', 'other_natural']]
disturbed_2015 = disturbed_2015.head(20)
disturbed_2015 = disturbed_2015.tail(1)
disturbed_2015['year'] = '2015'

######

# 2014
disturbed_2014 = dict_trees2014.get('Tab 8')
disturbed_2014.columns = ['drop', 'insects', 'disease', 'weather', 'fire', 'domestic_animals', 'wild_animals', 'humans', 'other_natural']
disturbed_2014 = disturbed_2014[['insects', 'disease', 'weather', 'fire', 'domestic_animals', 'wild_animals', 'humans', 'other_natural']]
disturbed_2014 = disturbed_2014.head(20)
disturbed_2014 = disturbed_2014.tail(1)
disturbed_2014['year'] = '2014'

######

# 2013
disturbed_2013 = dict_trees2013.get('Tab 8')
disturbed_2013.columns = ['drop', 'insects', 'disease', 'weather', 'fire', 'domestic_animals', 'wild_animals', 'humans', 'other_natural']
disturbed_2013 = disturbed_2013[['insects', 'disease', 'weather', 'fire', 'domestic_animals', 'wild_animals', 'humans', 'other_natural']]
disturbed_2013 = disturbed_2013.head(19)
disturbed_2013 = disturbed_2013.tail(1)
disturbed_2013['year'] = '2013'

######

# 2012
disturbed_2012 = dict_trees2012.get('Tab 8')
disturbed_2012.columns = ['drop', 'insects', 'disease', 'weather', 'fire', 'domestic_animals', 'wild_animals', 'humans', 'other_natural']
disturbed_2012 = disturbed_2012[['insects', 'disease', 'weather', 'fire', 'domestic_animals', 'wild_animals', 'humans', 'other_natural']]
disturbed_2012 = disturbed_2012.head(20)
disturbed_2012 = disturbed_2012.tail(1)
disturbed_2012['year'] = '2012'

######

# 2011
disturbed_2011 = dict_trees2011.get('Tab 8')
disturbed_2011.columns = ['drop', 'insects', 'disease', 'weather', 'fire', 'domestic_animals', 'wild_animals', 'humans', 'other_natural']
disturbed_2011 = disturbed_2011[['insects', 'disease', 'weather', 'fire', 'domestic_animals', 'wild_animals', 'humans', 'other_natural']]
disturbed_2011 = disturbed_2011.head(20)
disturbed_2011 = disturbed_2011.tail(1)
disturbed_2011['year'] = '2011'

######

# 2010
disturbed_2010 = dict_trees2010.get('Tab 8')
disturbed_2010.columns = ['drop', 'insects', 'disease', 'weather', 'fire', 'domestic_animals', 'wild_animals', 'humans', 'other_natural']
disturbed_2010 = disturbed_2010[['insects', 'disease', 'weather', 'fire', 'domestic_animals', 'wild_animals', 'humans', 'other_natural']]
disturbed_2010 = disturbed_2010.head(20)
disturbed_2010 = disturbed_2010.tail(1)
disturbed_2010['year'] = '2010'

######

# 2009
disturbed_2009 = dict_trees2009.get('Tab 8')
disturbed_2009.columns = ['drop', 'insects', 'disease', 'weather', 'fire', 'domestic_animals', 'wild_animals', 'humans', 'other_natural']
disturbed_2009 = disturbed_2009[['insects', 'disease', 'weather', 'fire', 'domestic_animals', 'wild_animals', 'humans', 'other_natural']]
disturbed_2009 = disturbed_2009.head(20)
disturbed_2009 = disturbed_2009.tail(1)
disturbed_2009['year'] = '2009'

######

# 2008
disturbed_2008 = dict_trees2008.get('Tab 8')
disturbed_2008.columns = ['drop', 'insects', 'disease', 'weather', 'fire', 'domestic_animals', 'wild_animals', 'humans', 'other_natural']
disturbed_2008 = disturbed_2008[['insects', 'disease', 'weather', 'fire', 'domestic_animals', 'wild_animals', 'humans', 'other_natural']]
disturbed_2008 = disturbed_2008.head(20)
disturbed_2008 = disturbed_2008.tail(1)
disturbed_2008['year'] = '2008'

######

# 2007
disturbed_2007 = dict_trees2007.get('Tab 8')
disturbed_2007.columns = ['drop', 'insects', 'disease', 'weather', 'fire', 'domestic_animals', 'wild_animals', 'humans', 'other_natural']
disturbed_2007 = disturbed_2007[['insects', 'disease', 'weather', 'fire', 'domestic_animals', 'wild_animals', 'humans', 'other_natural']]
disturbed_2007 = disturbed_2007.head(19)
disturbed_2007 = disturbed_2007.tail(1)
disturbed_2007['year'] = '2007'

# combining all tables
disturbed = pd.concat([disturbed_2007, disturbed_2008, disturbed_2009, disturbed_2010, disturbed_2011, disturbed_2012, disturbed_2013, disturbed_2014, disturbed_2015, disturbed_2016])
disturbed = disturbed.reset_index(drop=True)
disturbed = disturbed[['year', 'insects', 'disease', 'weather', 'fire', 'domestic_animals', 'wild_animals', 'humans', 'other_natural']]

# changing data type to numeric
disturbed.insects = pd.to_numeric(disturbed.insects)
disturbed.disease = pd.to_numeric(disturbed.disease)
disturbed.weather = pd.to_numeric(disturbed.weather)
disturbed.fire = pd.to_numeric(disturbed.fire)
disturbed.domestic_animals = pd.to_numeric(disturbed.domestic_animals)
disturbed.wild_animals = pd.to_numeric(disturbed.wild_animals)
disturbed.humans = pd.to_numeric(disturbed.humans)
disturbed.other_natural = pd.to_numeric(disturbed.other_natural)

# adding total disturbed column
disturbed['total_disturbed'] = disturbed.insects+disturbed.disease+disturbed.weather+disturbed.fire+disturbed.domestic_animals+disturbed.wild_animals+disturbed.humans+disturbed.other_natural

# adding perc columns
disturbed['perc_insects'] = round(disturbed.insects/disturbed.total_disturbed*100, 2)
disturbed['perc_disease'] = round(disturbed.disease/disturbed.total_disturbed*100, 2)
disturbed['perc_weather'] = round(disturbed.weather/disturbed.total_disturbed*100, 2)
disturbed['perc_fire'] = round(disturbed.fire/disturbed.total_disturbed*100, 2)
disturbed['perc_domestic_animals'] = round(disturbed.domestic_animals/disturbed.total_disturbed*100, 2)
disturbed['perc_wild_animals'] = round(disturbed.wild_animals/disturbed.total_disturbed*100, 2)
disturbed['perc_humans'] = round(disturbed.humans/disturbed.total_disturbed*100, 2)
disturbed['perc_other_natural'] = round(disturbed.other_natural/disturbed.total_disturbed*100, 2)

# fixing format
disturbed_sub = pd.melt(disturbed, id_vars='year', value_vars=['insects', 'disease', 'weather', 'fire', 'domestic_animals', 'wild_animals', 'humans', 'other_natural', 'total_disturbed'])
disturbed_sub.columns = ['year', 'class_type', 'thousand_acres']
disturbed_perc = disturbed.drop(columns=['insects', 'disease', 'weather', 'fire', 'domestic_animals', 'wild_animals', 'humans', 'other_natural', 'total_disturbed'])
disturbed_perc.columns = ['year', 'insects', 'disease', 'weather', 'fire', 'domestic_animals', 'wild_animals', 'humans', 'other_natural']
disturbed_perc = pd.melt(disturbed_perc, id_vars='year', value_vars=['year', 'insects', 'disease', 'weather', 'fire', 'domestic_animals', 'wild_animals', 'humans', 'other_natural'])
disturbed_perc.columns = ['year', 'class_type', 'perc_total_land']
disturbed = pd.merge(disturbed_sub, disturbed_perc, on=['year', 'class_type'], how='outer')

In [5]:
## Table 10
## Land by Tree Species, in million trees

# 2016
type_2016 = dict_trees2016.get('Tab 10')
type_2016.columns = ['class_type', 'all_tree_species', 'drop1', 'drop2', 'drop3', 'drop4', 'drop5', 'drop6', 'drop7', 'drop8', 'drop9', 'drop10', 'drop11', 'drop12', 'drop13', 'drop14', 'drop15']
type_2016 = type_2016.head(34)
type_2016 = type_2016.tail(31)
type_2016 = type_2016.reset_index(drop=True)
type_2016 = type_2016[['class_type', 'all_tree_species']]

type_2016.at[1, 'class_type']='loblolly_and_shortleaf_pines'
type_2016.at[2, 'class_type']='other_yellow_pines'
type_2016.at[3, 'class_type']='eastern_white_and_red_pines'
type_2016.at[4, 'class_type']='spruce_and_balsam_fir'
type_2016.at[5, 'class_type']='eastern_hemlock'
type_2016.at[6, 'class_type']='cypress'
type_2016.at[7, 'class_type']='other_eastern_softwoods'
type_2016.at[8, 'class_type']='total_softwoods'
type_2016.at[10, 'class_type']='select_white_oaks'
type_2016.at[11, 'class_type']='select_red_oaks'
type_2016.at[12, 'class_type']='other_white_oaks'
type_2016.at[13, 'class_type']='other_red_oaks'
type_2016.at[14, 'class_type']='hickory'
type_2016.at[15, 'class_type']='yellow_birch'
type_2016.at[16, 'class_type']='hard_maple'
type_2016.at[17, 'class_type']='soft_maple'
type_2016.at[18, 'class_type']='beech'
type_2016.at[19, 'class_type']='sweetgum'
type_2016.at[20, 'class_type']='tupelo_and_blackgum'
type_2016.at[21, 'class_type']='ash'
type_2016.at[22, 'class_type']='cottonwood_and_aspen'
type_2016.at[23, 'class_type']='basswood'
type_2016.at[24, 'class_type']='yellow_poplar'
type_2016.at[25, 'class_type']='black_walnut'
type_2016.at[26, 'class_type']='other_eastern_soft_hardwoods'
type_2016.at[27, 'class_type']='other_eastern_hard_hardwoods'
type_2016.at[28, 'class_type']='eastern_noncommercial_hardwoods'
type_2016.at[29, 'class_type']='total_hardwoods'
type_2016.at[30, 'class_type']='total_trees'

type_2016 = type_2016.set_index('class_type')
type_2016 = type_2016.transpose().reset_index(drop=True)
type_2016['year'] = '2016'
type_2016 = type_2016.drop(columns=['Softwood', 'Hardwood'])

######

# 2015
type_2015 = dict_trees2015.get('Tab 10')
type_2015.columns = ['class_type', 'all_tree_species', 'drop1', 'drop2', 'drop3', 'drop4', 'drop5', 'drop6', 'drop7', 'drop8', 'drop9', 'drop10', 'drop11', 'drop12', 'drop13', 'drop14', 'drop15']
type_2015 = type_2015.head(34)
type_2015 = type_2015.tail(31)
type_2015 = type_2015.reset_index(drop=True)
type_2015 = type_2015[['class_type', 'all_tree_species']]

type_2015.at[1, 'class_type']='loblolly_and_shortleaf_pines'
type_2015.at[2, 'class_type']='other_yellow_pines'
type_2015.at[3, 'class_type']='eastern_white_and_red_pines'
type_2015.at[4, 'class_type']='spruce_and_balsam_fir'
type_2015.at[5, 'class_type']='eastern_hemlock'
type_2015.at[6, 'class_type']='cypress'
type_2015.at[7, 'class_type']='other_eastern_softwoods'
type_2015.at[8, 'class_type']='total_softwoods'
type_2015.at[10, 'class_type']='select_white_oaks'
type_2015.at[11, 'class_type']='select_red_oaks'
type_2015.at[12, 'class_type']='other_white_oaks'
type_2015.at[13, 'class_type']='other_red_oaks'
type_2015.at[14, 'class_type']='hickory'
type_2015.at[15, 'class_type']='yellow_birch'
type_2015.at[16, 'class_type']='hard_maple'
type_2015.at[17, 'class_type']='soft_maple'
type_2015.at[18, 'class_type']='beech'
type_2015.at[19, 'class_type']='sweetgum'
type_2015.at[20, 'class_type']='tupelo_and_blackgum'
type_2015.at[21, 'class_type']='ash'
type_2015.at[22, 'class_type']='cottonwood_and_aspen'
type_2015.at[23, 'class_type']='basswood'
type_2015.at[24, 'class_type']='yellow_poplar'
type_2015.at[25, 'class_type']='black_walnut'
type_2015.at[26, 'class_type']='other_eastern_soft_hardwoods'
type_2015.at[27, 'class_type']='other_eastern_hard_hardwoods'
type_2015.at[28, 'class_type']='eastern_noncommercial_hardwoods'
type_2015.at[29, 'class_type']='total_hardwoods'
type_2015.at[30, 'class_type']='total_trees'

type_2015 = type_2015.set_index('class_type')
type_2015 = type_2015.transpose().reset_index(drop=True)
type_2015['year'] = '2015'
type_2015 = type_2015.drop(columns=['Softwood', 'Hardwood'])

######

# 2014
type_2014 = dict_trees2014.get('Tab 10')
type_2014.columns = ['class_type', 'all_tree_species', 'drop1', 'drop2', 'drop3', 'drop4', 'drop5', 'drop6', 'drop7', 'drop8', 'drop9', 'drop10', 'drop11', 'drop12', 'drop13', 'drop14', 'drop15']
type_2014 = type_2014.head(34)
type_2014 = type_2014.tail(31)
type_2014 = type_2014.reset_index(drop=True)
type_2014 = type_2014[['class_type', 'all_tree_species']]

type_2014.at[1, 'class_type']='loblolly_and_shortleaf_pines'
type_2014.at[2, 'class_type']='other_yellow_pines'
type_2014.at[3, 'class_type']='eastern_white_and_red_pines'
type_2014.at[4, 'class_type']='spruce_and_balsam_fir'
type_2014.at[5, 'class_type']='eastern_hemlock'
type_2014.at[6, 'class_type']='cypress'
type_2014.at[7, 'class_type']='other_eastern_softwoods'
type_2014.at[8, 'class_type']='total_softwoods'
type_2014.at[10, 'class_type']='select_white_oaks'
type_2014.at[11, 'class_type']='select_red_oaks'
type_2014.at[12, 'class_type']='other_white_oaks'
type_2014.at[13, 'class_type']='other_red_oaks'
type_2014.at[14, 'class_type']='hickory'
type_2014.at[15, 'class_type']='yellow_birch'
type_2014.at[16, 'class_type']='hard_maple'
type_2014.at[17, 'class_type']='soft_maple'
type_2014.at[18, 'class_type']='beech'
type_2014.at[19, 'class_type']='sweetgum'
type_2014.at[20, 'class_type']='tupelo_and_blackgum'
type_2014.at[21, 'class_type']='ash'
type_2014.at[22, 'class_type']='cottonwood_and_aspen'
type_2014.at[23, 'class_type']='basswood'
type_2014.at[24, 'class_type']='yellow_poplar'
type_2014.at[25, 'class_type']='black_walnut'
type_2014.at[26, 'class_type']='other_eastern_soft_hardwoods'
type_2014.at[27, 'class_type']='other_eastern_hard_hardwoods'
type_2014.at[28, 'class_type']='eastern_noncommercial_hardwoods'
type_2014.at[29, 'class_type']='total_hardwoods'
type_2014.at[30, 'class_type']='total_trees'

type_2014 = type_2014.set_index('class_type')
type_2014 = type_2014.transpose().reset_index(drop=True)
type_2014['year'] = '2014'
type_2014 = type_2014.drop(columns=['Softwood', 'Hardwood'])

######

# 2013
type_2013 = dict_trees2013.get('Tab 10')
type_2013.columns = ['class_type', 'all_tree_species', 'drop1', 'drop2', 'drop3', 'drop4', 'drop5', 'drop6', 'drop7', 'drop8', 'drop9', 'drop10', 'drop11', 'drop12', 'drop13', 'drop14', 'drop15']
type_2013 = type_2013.head(34)
type_2013 = type_2013.tail(31)
type_2013 = type_2013.reset_index(drop=True)
type_2013 = type_2013[['class_type', 'all_tree_species']]

type_2013.at[1, 'class_type']='loblolly_and_shortleaf_pines'
type_2013.at[2, 'class_type']='other_yellow_pines'
type_2013.at[3, 'class_type']='eastern_white_and_red_pines'
type_2013.at[4, 'class_type']='spruce_and_balsam_fir'
type_2013.at[5, 'class_type']='eastern_hemlock'
type_2013.at[6, 'class_type']='cypress'
type_2013.at[7, 'class_type']='other_eastern_softwoods'
type_2013.at[8, 'class_type']='total_softwoods'
type_2013.at[10, 'class_type']='select_white_oaks'
type_2013.at[11, 'class_type']='select_red_oaks'
type_2013.at[12, 'class_type']='other_white_oaks'
type_2013.at[13, 'class_type']='other_red_oaks'
type_2013.at[14, 'class_type']='hickory'
type_2013.at[15, 'class_type']='yellow_birch'
type_2013.at[16, 'class_type']='hard_maple'
type_2013.at[17, 'class_type']='soft_maple'
type_2013.at[18, 'class_type']='beech'
type_2013.at[19, 'class_type']='sweetgum'
type_2013.at[20, 'class_type']='tupelo_and_blackgum'
type_2013.at[21, 'class_type']='ash'
type_2013.at[22, 'class_type']='cottonwood_and_aspen'
type_2013.at[23, 'class_type']='basswood'
type_2013.at[24, 'class_type']='yellow_poplar'
type_2013.at[25, 'class_type']='black_walnut'
type_2013.at[26, 'class_type']='other_eastern_soft_hardwoods'
type_2013.at[27, 'class_type']='other_eastern_hard_hardwoods'
type_2013.at[28, 'class_type']='eastern_noncommercial_hardwoods'
type_2013.at[29, 'class_type']='total_hardwoods'
type_2013.at[30, 'class_type']='total_trees'

type_2013 = type_2013.set_index('class_type')
type_2013 = type_2013.transpose().reset_index(drop=True)
type_2013['year'] = '2013'
type_2013 = type_2013.drop(columns=['Softwood', 'Hardwood'])

######

# 2012
type_2012 = dict_trees2012.get('Tab 10')
type_2012.columns = ['class_type', 'all_tree_species', 'drop1', 'drop2', 'drop3', 'drop4', 'drop5', 'drop6', 'drop7', 'drop8', 'drop9', 'drop10', 'drop11', 'drop12', 'drop13', 'drop14', 'drop15']
type_2012 = type_2012.head(34)
type_2012 = type_2012.tail(31)
type_2012 = type_2012.reset_index(drop=True)
type_2012 = type_2012[['class_type', 'all_tree_species']]

type_2012.at[1, 'class_type']='loblolly_and_shortleaf_pines'
type_2012.at[2, 'class_type']='other_yellow_pines'
type_2012.at[3, 'class_type']='eastern_white_and_red_pines'
type_2012.at[4, 'class_type']='spruce_and_balsam_fir'
type_2012.at[5, 'class_type']='eastern_hemlock'
type_2012.at[6, 'class_type']='cypress'
type_2012.at[7, 'class_type']='other_eastern_softwoods'
type_2012.at[8, 'class_type']='total_softwoods'
type_2012.at[10, 'class_type']='select_white_oaks'
type_2012.at[11, 'class_type']='select_red_oaks'
type_2012.at[12, 'class_type']='other_white_oaks'
type_2012.at[13, 'class_type']='other_red_oaks'
type_2012.at[14, 'class_type']='hickory'
type_2012.at[15, 'class_type']='yellow_birch'
type_2012.at[16, 'class_type']='hard_maple'
type_2012.at[17, 'class_type']='soft_maple'
type_2012.at[18, 'class_type']='beech'
type_2012.at[19, 'class_type']='sweetgum'
type_2012.at[20, 'class_type']='tupelo_and_blackgum'
type_2012.at[21, 'class_type']='ash'
type_2012.at[22, 'class_type']='cottonwood_and_aspen'
type_2012.at[23, 'class_type']='basswood'
type_2012.at[24, 'class_type']='yellow_poplar'
type_2012.at[25, 'class_type']='black_walnut'
type_2012.at[26, 'class_type']='other_eastern_soft_hardwoods'
type_2012.at[27, 'class_type']='other_eastern_hard_hardwoods'
type_2012.at[28, 'class_type']='eastern_noncommercial_hardwoods'
type_2012.at[29, 'class_type']='total_hardwoods'
type_2012.at[30, 'class_type']='total_trees'

type_2012 = type_2012.set_index('class_type')
type_2012 = type_2012.transpose().reset_index(drop=True)
type_2012['year'] = '2012'
type_2012 = type_2012.drop(columns=['Softwood', 'Hardwood'])

######

# 2011
type_2011 = dict_trees2011.get('Tab 10')
type_2011.columns = ['class_type', 'all_tree_species', 'drop1', 'drop2', 'drop3', 'drop4', 'drop5', 'drop6', 'drop7', 'drop8', 'drop9', 'drop10', 'drop11', 'drop12', 'drop13', 'drop14', 'drop15']
type_2011 = type_2011.head(34)
type_2011 = type_2011.tail(31)
type_2011 = type_2011.reset_index(drop=True)
type_2011 = type_2011[['class_type', 'all_tree_species']]

type_2011.at[1, 'class_type']='loblolly_and_shortleaf_pines'
type_2011.at[2, 'class_type']='other_yellow_pines'
type_2011.at[3, 'class_type']='eastern_white_and_red_pines'
type_2011.at[4, 'class_type']='spruce_and_balsam_fir'
type_2011.at[5, 'class_type']='eastern_hemlock'
type_2011.at[6, 'class_type']='cypress'
type_2011.at[7, 'class_type']='other_eastern_softwoods'
type_2011.at[8, 'class_type']='total_softwoods'
type_2011.at[10, 'class_type']='select_white_oaks'
type_2011.at[11, 'class_type']='select_red_oaks'
type_2011.at[12, 'class_type']='other_white_oaks'
type_2011.at[13, 'class_type']='other_red_oaks'
type_2011.at[14, 'class_type']='hickory'
type_2011.at[15, 'class_type']='yellow_birch'
type_2011.at[16, 'class_type']='hard_maple'
type_2011.at[17, 'class_type']='soft_maple'
type_2011.at[18, 'class_type']='beech'
type_2011.at[19, 'class_type']='sweetgum'
type_2011.at[20, 'class_type']='tupelo_and_blackgum'
type_2011.at[21, 'class_type']='ash'
type_2011.at[22, 'class_type']='cottonwood_and_aspen'
type_2011.at[23, 'class_type']='basswood'
type_2011.at[24, 'class_type']='yellow_poplar'
type_2011.at[25, 'class_type']='black_walnut'
type_2011.at[26, 'class_type']='other_eastern_soft_hardwoods'
type_2011.at[27, 'class_type']='other_eastern_hard_hardwoods'
type_2011.at[28, 'class_type']='eastern_noncommercial_hardwoods'
type_2011.at[29, 'class_type']='total_hardwoods'
type_2011.at[30, 'class_type']='total_trees'

type_2011 = type_2011.set_index('class_type')
type_2011 = type_2011.transpose().reset_index(drop=True)
type_2011['year'] = '2011'
type_2011 = type_2011.drop(columns=['Softwood', 'Hardwood'])

######

# 2010
type_2010 = dict_trees2010.get('Tab 10')
type_2010.columns = ['class_type', 'all_tree_species', 'drop1', 'drop2', 'drop3', 'drop4', 'drop5', 'drop6', 'drop7', 'drop8', 'drop9', 'drop10', 'drop11', 'drop12', 'drop13', 'drop14', 'drop15']
type_2010 = type_2010.head(34)
type_2010 = type_2010.tail(31)
type_2010 = type_2010.reset_index(drop=True)
type_2010 = type_2010[['class_type', 'all_tree_species']]

type_2010.at[1, 'class_type']='loblolly_and_shortleaf_pines'
type_2010.at[2, 'class_type']='other_yellow_pines'
type_2010.at[3, 'class_type']='eastern_white_and_red_pines'
type_2010.at[4, 'class_type']='spruce_and_balsam_fir'
type_2010.at[5, 'class_type']='eastern_hemlock'
type_2010.at[6, 'class_type']='cypress'
type_2010.at[7, 'class_type']='other_eastern_softwoods'
type_2010.at[8, 'class_type']='total_softwoods'
type_2010.at[10, 'class_type']='select_white_oaks'
type_2010.at[11, 'class_type']='select_red_oaks'
type_2010.at[12, 'class_type']='other_white_oaks'
type_2010.at[13, 'class_type']='other_red_oaks'
type_2010.at[14, 'class_type']='hickory'
type_2010.at[15, 'class_type']='yellow_birch'
type_2010.at[16, 'class_type']='hard_maple'
type_2010.at[17, 'class_type']='soft_maple'
type_2010.at[18, 'class_type']='beech'
type_2010.at[19, 'class_type']='sweetgum'
type_2010.at[20, 'class_type']='tupelo_and_blackgum'
type_2010.at[21, 'class_type']='ash'
type_2010.at[22, 'class_type']='cottonwood_and_aspen'
type_2010.at[23, 'class_type']='basswood'
type_2010.at[24, 'class_type']='yellow_poplar'
type_2010.at[25, 'class_type']='black_walnut'
type_2010.at[26, 'class_type']='other_eastern_soft_hardwoods'
type_2010.at[27, 'class_type']='other_eastern_hard_hardwoods'
type_2010.at[28, 'class_type']='eastern_noncommercial_hardwoods'
type_2010.at[29, 'class_type']='total_hardwoods'
type_2010.at[30, 'class_type']='total_trees'

type_2010 = type_2010.set_index('class_type')
type_2010 = type_2010.transpose().reset_index(drop=True)
type_2010['year'] = '2010'
type_2010 = type_2010.drop(columns=['Softwood', 'Hardwood'])

######

# 2009
type_2009 = dict_trees2009.get('Tab 10')
type_2009.columns = ['class_type', 'all_tree_species', 'drop1', 'drop2', 'drop3', 'drop4', 'drop5', 'drop6', 'drop7', 'drop8', 'drop9', 'drop10', 'drop11', 'drop12', 'drop13', 'drop14', 'drop15']
type_2009 = type_2009.head(34)
type_2009 = type_2009.tail(31)
type_2009 = type_2009.reset_index(drop=True)
type_2009 = type_2009[['class_type', 'all_tree_species']]

type_2009.at[1, 'class_type']='loblolly_and_shortleaf_pines'
type_2009.at[2, 'class_type']='other_yellow_pines'
type_2009.at[3, 'class_type']='eastern_white_and_red_pines'
type_2009.at[4, 'class_type']='spruce_and_balsam_fir'
type_2009.at[5, 'class_type']='eastern_hemlock'
type_2009.at[6, 'class_type']='cypress'
type_2009.at[7, 'class_type']='other_eastern_softwoods'
type_2009.at[8, 'class_type']='total_softwoods'
type_2009.at[10, 'class_type']='select_white_oaks'
type_2009.at[11, 'class_type']='select_red_oaks'
type_2009.at[12, 'class_type']='other_white_oaks'
type_2009.at[13, 'class_type']='other_red_oaks'
type_2009.at[14, 'class_type']='hickory'
type_2009.at[15, 'class_type']='yellow_birch'
type_2009.at[16, 'class_type']='hard_maple'
type_2009.at[17, 'class_type']='soft_maple'
type_2009.at[18, 'class_type']='beech'
type_2009.at[19, 'class_type']='sweetgum'
type_2009.at[20, 'class_type']='tupelo_and_blackgum'
type_2009.at[21, 'class_type']='ash'
type_2009.at[22, 'class_type']='cottonwood_and_aspen'
type_2009.at[23, 'class_type']='basswood'
type_2009.at[24, 'class_type']='yellow_poplar'
type_2009.at[25, 'class_type']='black_walnut'
type_2009.at[26, 'class_type']='other_eastern_soft_hardwoods'
type_2009.at[27, 'class_type']='other_eastern_hard_hardwoods'
type_2009.at[28, 'class_type']='eastern_noncommercial_hardwoods'
type_2009.at[29, 'class_type']='total_hardwoods'
type_2009.at[30, 'class_type']='total_trees'

type_2009 = type_2009.set_index('class_type')
type_2009 = type_2009.transpose().reset_index(drop=True)
type_2009['year'] = '2009'
type_2009 = type_2009.drop(columns=['Softwood', 'Hardwood'])

######

# 2008
type_2008 = dict_trees2008.get('Tab 10')
type_2008.columns = ['class_type', 'all_tree_species', 'drop1', 'drop2', 'drop3', 'drop4', 'drop5', 'drop6', 'drop7', 'drop8', 'drop9', 'drop10', 'drop11', 'drop12', 'drop13', 'drop14', 'drop15']
type_2008 = type_2008.head(34)
type_2008 = type_2008.tail(31)
type_2008 = type_2008.reset_index(drop=True)
type_2008 = type_2008[['class_type', 'all_tree_species']]

type_2008.at[1, 'class_type']='loblolly_and_shortleaf_pines'
type_2008.at[2, 'class_type']='other_yellow_pines'
type_2008.at[3, 'class_type']='eastern_white_and_red_pines'
type_2008.at[4, 'class_type']='spruce_and_balsam_fir'
type_2008.at[5, 'class_type']='eastern_hemlock'
type_2008.at[6, 'class_type']='cypress'
type_2008.at[7, 'class_type']='other_eastern_softwoods'
type_2008.at[8, 'class_type']='total_softwoods'
type_2008.at[10, 'class_type']='select_white_oaks'
type_2008.at[11, 'class_type']='select_red_oaks'
type_2008.at[12, 'class_type']='other_white_oaks'
type_2008.at[13, 'class_type']='other_red_oaks'
type_2008.at[14, 'class_type']='hickory'
type_2008.at[15, 'class_type']='yellow_birch'
type_2008.at[16, 'class_type']='hard_maple'
type_2008.at[17, 'class_type']='soft_maple'
type_2008.at[18, 'class_type']='beech'
type_2008.at[19, 'class_type']='sweetgum'
type_2008.at[20, 'class_type']='tupelo_and_blackgum'
type_2008.at[21, 'class_type']='ash'
type_2008.at[22, 'class_type']='cottonwood_and_aspen'
type_2008.at[23, 'class_type']='basswood'
type_2008.at[24, 'class_type']='yellow_poplar'
type_2008.at[25, 'class_type']='black_walnut'
type_2008.at[26, 'class_type']='other_eastern_soft_hardwoods'
type_2008.at[27, 'class_type']='other_eastern_hard_hardwoods'
type_2008.at[28, 'class_type']='eastern_noncommercial_hardwoods'
type_2008.at[29, 'class_type']='total_hardwoods'
type_2008.at[30, 'class_type']='total_trees'

type_2008 = type_2008.set_index('class_type')
type_2008 = type_2008.transpose().reset_index(drop=True)
type_2008['year'] = '2008'
type_2008 = type_2008.drop(columns=['Softwood', 'Hardwood'])

######

# 2007
type_2007 = dict_trees2007.get('Tab 10')
type_2007.columns = ['class_type', 'all_tree_species', 'drop1', 'drop2', 'drop3', 'drop4', 'drop5', 'drop6', 'drop7', 'drop8', 'drop9', 'drop10', 'drop11', 'drop12', 'drop13', 'drop14', 'drop15']
type_2007 = type_2007.head(34)
type_2007 = type_2007.tail(31)
type_2007 = type_2007.reset_index(drop=True)
type_2007 = type_2007[['class_type', 'all_tree_species']]

type_2007.at[1, 'class_type']='loblolly_and_shortleaf_pines'
type_2007.at[2, 'class_type']='other_yellow_pines'
type_2007.at[3, 'class_type']='eastern_white_and_red_pines'
type_2007.at[4, 'class_type']='spruce_and_balsam_fir'
type_2007.at[5, 'class_type']='eastern_hemlock'
type_2007.at[6, 'class_type']='cypress'
type_2007.at[7, 'class_type']='other_eastern_softwoods'
type_2007.at[8, 'class_type']='total_softwoods'
type_2007.at[10, 'class_type']='select_white_oaks'
type_2007.at[11, 'class_type']='select_red_oaks'
type_2007.at[12, 'class_type']='other_white_oaks'
type_2007.at[13, 'class_type']='other_red_oaks'
type_2007.at[14, 'class_type']='hickory'
type_2007.at[15, 'class_type']='yellow_birch'
type_2007.at[16, 'class_type']='hard_maple'
type_2007.at[17, 'class_type']='soft_maple'
type_2007.at[18, 'class_type']='beech'
type_2007.at[19, 'class_type']='sweetgum'
type_2007.at[20, 'class_type']='tupelo_and_blackgum'
type_2007.at[21, 'class_type']='ash'
type_2007.at[22, 'class_type']='cottonwood_and_aspen'
type_2007.at[23, 'class_type']='basswood'
type_2007.at[24, 'class_type']='yellow_poplar'
type_2007.at[25, 'class_type']='black_walnut'
type_2007.at[26, 'class_type']='other_eastern_soft_hardwoods'
type_2007.at[27, 'class_type']='other_eastern_hard_hardwoods'
type_2007.at[28, 'class_type']='eastern_noncommercial_hardwoods'
type_2007.at[29, 'class_type']='total_hardwoods'
type_2007.at[30, 'class_type']='total_trees'

type_2007 = type_2007.set_index('class_type')
type_2007 = type_2007.transpose().reset_index(drop=True)
type_2007['year'] = '2007'
type_2007 = type_2007.drop(columns=['Softwood', 'Hardwood'])

# combining all tables
species = pd.concat([type_2007, type_2008, type_2009, type_2010, type_2011, type_2012, type_2013, type_2014, type_2015, type_2016])
species = species.reset_index(drop=True)

# changing data type to numeric
species.loblolly_and_shortleaf_pines = pd.to_numeric(species.loblolly_and_shortleaf_pines)
species.other_yellow_pines = pd.to_numeric(species.other_yellow_pines)
species.eastern_white_and_red_pines = pd.to_numeric(species.eastern_white_and_red_pines)
species.spruce_and_balsam_fir = pd.to_numeric(species.spruce_and_balsam_fir)
species.eastern_hemlock = pd.to_numeric(species.eastern_hemlock)
species.cypress = pd.to_numeric(species.cypress)
species.other_eastern_softwoods = pd.to_numeric(species.other_eastern_softwoods)
species.total_softwoods = pd.to_numeric(species.total_softwoods)
species.select_white_oaks = pd.to_numeric(species.select_white_oaks)
species.select_red_oaks = pd.to_numeric(species.select_red_oaks)
species.other_white_oaks = pd.to_numeric(species.other_white_oaks)
species.other_red_oaks = pd.to_numeric(species.other_red_oaks)
species.hickory = pd.to_numeric(species.hickory)
species.yellow_birch = pd.to_numeric(species.yellow_birch)
species.hard_maple = pd.to_numeric(species.hard_maple)
species.soft_maple = pd.to_numeric(species.soft_maple)
species.beech = pd.to_numeric(species.beech)
species.sweetgum = pd.to_numeric(species.sweetgum)
species.tupelo_and_blackgum = pd.to_numeric(species.tupelo_and_blackgum)
species.ash = pd.to_numeric(species.ash)
species.cottonwood_and_aspen = pd.to_numeric(species.cottonwood_and_aspen)
species.basswood = pd.to_numeric(species.basswood)
species.yellow_poplar = pd.to_numeric(species.yellow_poplar)
species.black_walnut = pd.to_numeric(species.black_walnut)
species.other_eastern_soft_hardwoods = pd.to_numeric(species.other_eastern_soft_hardwoods)
species.other_eastern_hard_hardwoods = pd.to_numeric(species.other_eastern_hard_hardwoods)
species.eastern_noncommercial_hardwoods = pd.to_numeric(species.eastern_noncommercial_hardwoods)
species.total_hardwoods = pd.to_numeric(species.total_hardwoods)
species.total_trees = pd.to_numeric(species.total_trees)

# fixing format
species_sub = pd.melt(species, id_vars='year', value_vars=['loblolly_and_shortleaf_pines', 'other_yellow_pines', 'eastern_white_and_red_pines', 'spruce_and_balsam_fir', 'eastern_hemlock', 'cypress', 'other_eastern_softwoods', 'select_white_oaks', 'select_red_oaks', 'other_white_oaks', 'other_red_oaks', 'hickory', 'yellow_birch', 'hard_maple', 'soft_maple', 'beech', 'sweetgum', 'tupelo_and_blackgum', 'ash', 'cottonwood_and_aspen', 'basswood', 'yellow_poplar', 'black_walnut', 'other_eastern_soft_hardwoods', 'other_eastern_hard_hardwoods', 'eastern_noncommercial_hardwoods', 'total_trees'])
species_sub.columns = ['year', 'class_type', 'million_trees']
species = species_sub
species

     year                    class_type  million_trees
0    2007  loblolly_and_shortleaf_pines          272.6
1    2008  loblolly_and_shortleaf_pines          273.4
2    2009  loblolly_and_shortleaf_pines          275.5
3    2010  loblolly_and_shortleaf_pines          277.2
4    2011  loblolly_and_shortleaf_pines          291.6
..    ...                           ...            ...
265  2012                   total_trees         8041.6
266  2013                   total_trees         8192.6
267  2014                   total_trees         8248.0
268  2015                   total_trees         8345.8
269  2016                   total_trees         8423.9

[270 rows x 3 columns]

In [6]:
## Table 12
## Land by Volume Live Trees, in million cubic feet

# 2016
volume_2016 = dict_trees2016.get('Tab 12')
volume_2016.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
volume_2016 = volume_2016.head(28)
volume_2016 = volume_2016.tail(25)
volume_2016 = volume_2016.reset_index(drop=True)
volume_2016 = volume_2016[['class_type', 'all_forest_land']]

volume_2016.at[3, 'class_type']='us_forest_service'
volume_2016.at[9, 'class_type']='other_federal'
volume_2016.at[13, 'class_type']='state_and_local_gov'
volume_2016.at[17, 'class_type']='forest_industry'
volume_2016.at[23, 'class_type']='nonindustrial_private'
volume_2016.at[24, 'class_type']='total_volume'
volume_2016 = volume_2016.set_index('class_type')
volume_2016 = volume_2016.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'forest_industry', 'nonindustrial_private', 'total_volume']].reset_index(drop=True)
volume_2016['year'] = '2016'

######

# 2015
volume_2015 = dict_trees2015.get('Tab 12')
volume_2015.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
volume_2015 = volume_2015.head(21)
volume_2015 = volume_2015.tail(18)
volume_2015 = volume_2015.reset_index(drop=True)
volume_2015 = volume_2015[['class_type', 'all_forest_land']]

volume_2015.at[3, 'class_type']='us_forest_service'
volume_2015.at[9, 'class_type']='other_federal'
volume_2015.at[13, 'class_type']='state_and_local_gov'
volume_2015.at[16, 'class_type']='nonindustrial_private'
volume_2015.at[17, 'class_type']='total_volume'
volume_2015 = volume_2015.set_index('class_type')
volume_2015 = volume_2015.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_volume']].reset_index(drop=True)
volume_2015['year'] = '2015'

######

# 2014
volume_2014 = dict_trees2014.get('Tab 12')
volume_2014.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
volume_2014 = volume_2014.head(21)
volume_2014 = volume_2014.tail(18)
volume_2014 = volume_2014.reset_index(drop=True)
volume_2014 = volume_2014[['class_type', 'all_forest_land']]

volume_2014.at[3, 'class_type']='us_forest_service'
volume_2014.at[9, 'class_type']='other_federal'
volume_2014.at[13, 'class_type']='state_and_local_gov'
volume_2014.at[16, 'class_type']='nonindustrial_private'
volume_2014.at[17, 'class_type']='total_volume'
volume_2014 = volume_2014.set_index('class_type')
volume_2014 = volume_2014.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_volume']].reset_index(drop=True)
volume_2014['year'] = '2014'

######

# 2013
volume_2013 = dict_trees2013.get('Tab 12')
volume_2013.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
volume_2013 = volume_2013.head(21)
volume_2013 = volume_2013.tail(18)
volume_2013 = volume_2013.reset_index(drop=True)
volume_2013 = volume_2013[['class_type', 'all_forest_land']]

volume_2013.at[3, 'class_type']='us_forest_service'
volume_2013.at[9, 'class_type']='other_federal'
volume_2013.at[13, 'class_type']='state_and_local_gov'
volume_2013.at[16, 'class_type']='nonindustrial_private'
volume_2013.at[17, 'class_type']='total_volume'
volume_2013 = volume_2013.set_index('class_type')
volume_2013 = volume_2013.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_volume']].reset_index(drop=True)
volume_2013['year'] = '2013'

######

# 2012
volume_2012 = dict_trees2012.get('Tab 12')
volume_2012.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
volume_2012 = volume_2012.head(21)
volume_2012 = volume_2012.tail(18)
volume_2012 = volume_2012.reset_index(drop=True)
volume_2012 = volume_2012[['class_type', 'all_forest_land']]

volume_2012.at[3, 'class_type']='us_forest_service'
volume_2012.at[9, 'class_type']='other_federal'
volume_2012.at[13, 'class_type']='state_and_local_gov'
volume_2012.at[16, 'class_type']='nonindustrial_private'
volume_2012.at[17, 'class_type']='total_volume'
volume_2012 = volume_2012.set_index('class_type')
volume_2012 = volume_2012.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_volume']].reset_index(drop=True)
volume_2012['year'] = '2012'

######

# 2011
volume_2011 = dict_trees2011.get('Tab 12')
volume_2011.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
volume_2011 = volume_2011.head(21)
volume_2011 = volume_2011.tail(18)
volume_2011 = volume_2011.reset_index(drop=True)
volume_2011 = volume_2011[['class_type', 'all_forest_land']]

volume_2011.at[3, 'class_type']='us_forest_service'
volume_2011.at[9, 'class_type']='other_federal'
volume_2011.at[13, 'class_type']='state_and_local_gov'
volume_2011.at[16, 'class_type']='nonindustrial_private'
volume_2011.at[17, 'class_type']='total_volume'
volume_2011 = volume_2011.set_index('class_type')
volume_2011 = volume_2011.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_volume']].reset_index(drop=True)
volume_2011['year'] = '2011'

######

# 2010
volume_2010 = dict_trees2010.get('Tab 12')
volume_2010.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
volume_2010 = volume_2010.head(21)
volume_2010 = volume_2010.tail(18)
volume_2010 = volume_2010.reset_index(drop=True)
volume_2010 = volume_2010[['class_type', 'all_forest_land']]

volume_2010.at[3, 'class_type']='us_forest_service'
volume_2010.at[9, 'class_type']='other_federal'
volume_2010.at[13, 'class_type']='state_and_local_gov'
volume_2010.at[16, 'class_type']='nonindustrial_private'
volume_2010.at[17, 'class_type']='total_volume'
volume_2010 = volume_2010.set_index('class_type')
volume_2010 = volume_2010.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_volume']].reset_index(drop=True)
volume_2010['year'] = '2010'

######

# 2009
volume_2009 = dict_trees2009.get('Tab 12')
volume_2009.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
volume_2009 = volume_2009.head(21)
volume_2009 = volume_2009.tail(18)
volume_2009 = volume_2009.reset_index(drop=True)
volume_2009 = volume_2009[['class_type', 'all_forest_land']]

volume_2009.at[3, 'class_type']='us_forest_service'
volume_2009.at[9, 'class_type']='other_federal'
volume_2009.at[13, 'class_type']='state_and_local_gov'
volume_2009.at[16, 'class_type']='nonindustrial_private'
volume_2009.at[17, 'class_type']='total_volume'
volume_2009 = volume_2009.set_index('class_type')
volume_2009 = volume_2009.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_volume']].reset_index(drop=True)
volume_2009['year'] = '2009'

######

# 2008
volume_2008 = dict_trees2008.get('Tab 12')
volume_2008.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
volume_2008 = volume_2008.head(21)
volume_2008 = volume_2008.tail(18)
volume_2008 = volume_2008.reset_index(drop=True)
volume_2008 = volume_2008[['class_type', 'all_forest_land']]

volume_2008.at[3, 'class_type']='us_forest_service'
volume_2008.at[9, 'class_type']='other_federal'
volume_2008.at[13, 'class_type']='state_and_local_gov'
volume_2008.at[16, 'class_type']='nonindustrial_private'
volume_2008.at[17, 'class_type']='total_volume'
volume_2008 = volume_2008.set_index('class_type')
volume_2008 = volume_2008.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_volume']].reset_index(drop=True)
volume_2008['year'] = '2008'

######

# 2007
volume_2007 = dict_trees2007.get('Tab 12')
volume_2007.columns = ['class_type', 'all_forest_land', 'total_unreserved', 'timberland', 'unproductive', 'total_reserved', 'productive', 'unproductive_reserved']
volume_2007 = volume_2007.head(22)
volume_2007 = volume_2007.tail(19)
volume_2007 = volume_2007.reset_index(drop=True)
volume_2007 = volume_2007[['class_type', 'all_forest_land']]

volume_2007.at[3, 'class_type']='us_forest_service'
volume_2007.at[9, 'class_type']='other_federal'
volume_2007.at[14, 'class_type']='state_and_local_gov'
volume_2007.at[17, 'class_type']='nonindustrial_private'
volume_2007.at[18, 'class_type']='total_volume'
volume_2007 = volume_2007.set_index('class_type')
volume_2007 = volume_2007.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_volume']].reset_index(drop=True)
volume_2007['year'] = '2007'

# combining all tables
volume = pd.concat([volume_2007, volume_2008, volume_2009, volume_2010, volume_2011, volume_2012, volume_2013, volume_2014, volume_2015, volume_2016])
volume = volume.reset_index(drop=True)
volume = volume[['year', 'us_forest_service', 'other_federal', 'state_and_local_gov', 'forest_industry', 'nonindustrial_private', 'total_volume']]

# changing data type to numeric
volume.us_forest_service = pd.to_numeric(volume.us_forest_service)
volume.other_federal = pd.to_numeric(volume.other_federal)
volume.state_and_local_gov = pd.to_numeric(volume.state_and_local_gov)
volume.forest_industry = pd.to_numeric(volume.forest_industry)
volume.nonindustrial_private = pd.to_numeric(volume.nonindustrial_private)
volume.total_volume = pd.to_numeric(volume.total_volume)

# adding perc columns
volume['perc_us_forest_service'] = round(volume.us_forest_service/volume.total_volume*100,2)
volume['perc_other_federal'] = round(volume.other_federal/volume.total_volume*100,2)
volume['perc_state_and_local_gov'] = round(volume.state_and_local_gov/volume.total_volume*100,2)
volume['perc_forest_industry'] = round(volume.forest_industry/volume.total_volume*100,2)
volume['perc_nonindustrial_private'] = round(volume.nonindustrial_private/volume.total_volume*100,2)

# fixing format
volume_sub = pd.melt(volume, id_vars='year', value_vars=['us_forest_service', 'other_federal', 'state_and_local_gov', 'forest_industry', 'nonindustrial_private', 'total_volume'])
volume_sub.columns = ['year', 'class_type', 'million_cubic_ft']
volume_perc = volume.drop(columns=['us_forest_service', 'other_federal', 'state_and_local_gov', 'forest_industry', 'nonindustrial_private', 'total_volume'])
volume_perc.columns = ['year', 'us_forest_service', 'other_federal', 'state_and_local_gov', 'forest_industry', 'nonindustrial_private']
volume_perc = pd.melt(volume_perc, id_vars='year', value_vars=['us_forest_service', 'other_federal', 'state_and_local_gov', 'forest_industry', 'nonindustrial_private'])
volume_perc.columns = ['year', 'class_type', 'perc_total_land']
volume = pd.merge(volume_sub, volume_perc, on=['year', 'class_type'], how='outer')
volume

    year             class_type  million_cubic_ft  perc_total_land
0   2007      us_forest_service            2048.1             7.16
1   2008      us_forest_service            2085.7             7.23
2   2009      us_forest_service            2087.4             7.15
3   2010      us_forest_service            2147.9             7.31
4   2011      us_forest_service            2127.1             7.22
5   2012      us_forest_service            2100.6             7.10
6   2013      us_forest_service            2163.7             7.19
7   2014      us_forest_service            2136.5             7.03
8   2015      us_forest_service            2134.7             6.87
9   2016      us_forest_service            2163.6             6.84
10  2007          other_federal            1754.2             6.13
11  2008          other_federal            1795.7             6.23
12  2009          other_federal            1830.6             6.27
13  2010          other_federal            1860.2             6.33
14  2011          other_federal            1903.0             6.46
15  2012          other_federal            1910.3             6.45
16  2013          other_federal            1916.1             6.37
17  2014          other_federal            1921.3             6.32
18  2015          other_federal            1952.0             6.28
19  2016          other_federal            1953.1             6.18
20  2007    state_and_local_gov            2005.9             7.01
21  2008    state_and_local_gov            2057.0             7.13
22  2009    state_and_local_gov            2154.6             7.38
23  2010    state_and_local_gov            2218.4             7.55
24  2011    state_and_local_gov            2318.5             7.87
25  2012    state_and_local_gov            2326.6             7.86
26  2013    state_and_local_gov            2475.3             8.23
27  2014    state_and_local_gov            2460.3             8.09
28  2015    state_and_local_gov            2542.0             8.18
29  2016    state_and_local_gov            2629.8             8.32
30  2007        forest_industry               NaN              NaN
31  2008        forest_industry               NaN              NaN
32  2009        forest_industry               NaN              NaN
33  2010        forest_industry               NaN              NaN
34  2011        forest_industry               NaN              NaN
35  2012        forest_industry               NaN              NaN
36  2013        forest_industry               NaN              NaN
37  2014        forest_industry               NaN              NaN
38  2015        forest_industry               NaN              NaN
39  2016        forest_industry             278.6             0.88
40  2007  nonindustrial_private           22799.5            79.70
41  2008  nonindustrial_private           22905.8            79.41
42  2009  nonindustrial_private           23113.0            79.19
43  2010  nonindustrial_private           23165.4            78.82
44  2011  nonindustrial_private           23114.3            78.45
45  2012  nonindustrial_private           23264.4            78.59
46  2013  nonindustrial_private           23528.3            78.21
47  2014  nonindustrial_private           23893.3            78.57
48  2015  nonindustrial_private           24449.1            78.67
49  2016  nonindustrial_private           24597.6            77.78
50  2007           total_volume           28607.6              NaN
51  2008           total_volume           28844.3              NaN
52  2009           total_volume           29185.6              NaN
53  2010           total_volume           29391.9              NaN
54  2011           total_volume           29463.0              NaN
55  2012           total_volume           29601.9              NaN
56  2013           total_volume           30083.4              NaN
57  2014           total_volume           30411.3              NaN
58  2015           total_volume           31077.8              NaN
59  2016           total_volume           31622.7              NaN

In [7]:
## Table 24
## Land by Tree Growth, in million cubic feet

# 2016
growth_2016 = dict_trees2016.get('Tab 24')
growth_2016.columns = ['class_type', 'timberland', 'forest_land']
growth_2016 = growth_2016.head(27)
growth_2016 = growth_2016.tail(25)
growth_2016 = growth_2016.reset_index(drop=True)

growth_2016.at[3, 'class_type']='us_forest_service'
growth_2016.at[9, 'class_type']='other_federal'
growth_2016.at[13, 'class_type']='state_and_local_gov'
growth_2016.at[17, 'class_type']='forest_industry'
growth_2016.at[23, 'class_type']='nonindustrial_private'
growth_2016.at[24, 'class_type']='total_land'
growth_2016 = growth_2016.set_index('class_type')
growth_2016 = growth_2016.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'forest_industry', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
growth_2016['land_type'] = ['timberland', 'forest land']
growth_2016['year'] = '2016'

######

# 2015
growth_2015 = dict_trees2015.get('Tab 24')
growth_2015.columns = ['class_type', 'timberland', 'forest_land']
growth_2015 = growth_2015.head(20)
growth_2015 = growth_2015.tail(18)
growth_2015 = growth_2015.reset_index(drop=True)

growth_2015.at[3, 'class_type']='us_forest_service'
growth_2015.at[9, 'class_type']='other_federal'
growth_2015.at[13, 'class_type']='state_and_local_gov'
growth_2015.at[16, 'class_type']='nonindustrial_private'
growth_2015.at[17, 'class_type']='total_land'
growth_2015 = growth_2015.set_index('class_type')
growth_2015 = growth_2015.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
growth_2015['land_type'] = ['timberland', 'forest land']
growth_2015['year'] = '2015'

######

# 2014
growth_2014 = dict_trees2014.get('Tab 24')
growth_2014.columns = ['class_type', 'timberland', 'forest_land']
growth_2014 = growth_2014.head(20)
growth_2014 = growth_2014.tail(18)
growth_2014 = growth_2014.reset_index(drop=True)

growth_2014.at[3, 'class_type']='us_forest_service'
growth_2014.at[9, 'class_type']='other_federal'
growth_2014.at[13, 'class_type']='state_and_local_gov'
growth_2014.at[16, 'class_type']='nonindustrial_private'
growth_2014.at[17, 'class_type']='total_land'
growth_2014 = growth_2014.set_index('class_type')
growth_2014 = growth_2014.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
growth_2014['land_type'] = ['timberland', 'forest land']
growth_2014['year'] = '2014'

######

# 2013
growth_2013 = dict_trees2013.get('Tab 24')
growth_2013.columns = ['class_type', 'timberland', 'forest_land']
growth_2013= growth_2013.head(20)
growth_2013 = growth_2013.tail(18)
growth_2013 = growth_2013.reset_index(drop=True)

growth_2013.at[3, 'class_type']='us_forest_service'
growth_2013.at[9, 'class_type']='other_federal'
growth_2013.at[13, 'class_type']='state_and_local_gov'
growth_2013.at[16, 'class_type']='nonindustrial_private'
growth_2013.at[17, 'class_type']='total_land'
growth_2013 = growth_2013.set_index('class_type')
growth_2013 = growth_2013.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
growth_2013['land_type'] = ['timberland', 'forest land']
growth_2013['year'] = '2013'

######

# 2012
growth_2012 = dict_trees2012.get('Tab 24')
growth_2012.columns = ['class_type', 'timberland', 'forest_land']
growth_2012 = growth_2012.head(20)
growth_2012 = growth_2012.tail(18)
growth_2012 = growth_2012.reset_index(drop=True)

growth_2012.at[3, 'class_type']='us_forest_service'
growth_2012.at[9, 'class_type']='other_federal'
growth_2012.at[13, 'class_type']='state_and_local_gov'
growth_2012.at[16, 'class_type']='nonindustrial_private'
growth_2012.at[17, 'class_type']='total_land'
growth_2012 = growth_2012.set_index('class_type')
growth_2012 = growth_2012.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
growth_2012['land_type'] = ['timberland', 'forest land']
growth_2012['year'] = '2012'

######

# 2011
growth_2011 = dict_trees2011.get('Tab 24')
growth_2011.columns = ['class_type', 'timberland', 'forest_land']
growth_2011 = growth_2011.head(20)
growth_2011 = growth_2011.tail(18)
growth_2011 = growth_2011.reset_index(drop=True)

growth_2011.at[3, 'class_type']='us_forest_service'
growth_2011.at[9, 'class_type']='other_federal'
growth_2011.at[13, 'class_type']='state_and_local_gov'
growth_2011.at[16, 'class_type']='nonindustrial_private'
growth_2011.at[17, 'class_type']='total_land'
growth_2011 = growth_2011.set_index('class_type')
growth_2011 = growth_2011.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
growth_2011['land_type'] = ['timberland', 'forest land']
growth_2011['year'] = '2011'

######

# 2010
growth_2010 = dict_trees2010.get('Tab 24')
growth_2010.columns = ['class_type', 'timberland', 'forest_land']
growth_2010 = growth_2010.head(20)
growth_2010 = growth_2010.tail(18)
growth_2010 = growth_2010.reset_index(drop=True)

growth_2010.at[3, 'class_type']='us_forest_service'
growth_2010.at[9, 'class_type']='other_federal'
growth_2010.at[13, 'class_type']='state_and_local_gov'
growth_2010.at[16, 'class_type']='nonindustrial_private'
growth_2010.at[17, 'class_type']='total_land'
growth_2010 = growth_2010.set_index('class_type')
growth_2010 = growth_2010.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
growth_2010['land_type'] = ['timberland', 'forest land']
growth_2010['year'] = '2010'

######

# 2009
growth_2009 = dict_trees2009.get('Tab 24')
growth_2009.columns = ['class_type', 'timberland', 'forest_land']
growth_2009 = growth_2009.head(20)
growth_2009 = growth_2009.tail(18)
growth_2009 = growth_2009.reset_index(drop=True)

growth_2009.at[3, 'class_type']='us_forest_service'
growth_2009.at[9, 'class_type']='other_federal'
growth_2009.at[13, 'class_type']='state_and_local_gov'
growth_2009.at[16, 'class_type']='nonindustrial_private'
growth_2009.at[17, 'class_type']='total_land'
growth_2009 = growth_2009.set_index('class_type')
growth_2009 = growth_2009.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
growth_2009['land_type'] = ['timberland', 'forest land']
growth_2009['year'] = '2009'

######

# 2008
growth_2008 = dict_trees2008.get('Tab 24')
growth_2008.columns = ['class_type', 'timberland', 'forest_land']
growth_2008 = growth_2008.head(20)
growth_2008 = growth_2008.tail(18)
growth_2008 = growth_2008.reset_index(drop=True)

growth_2008.at[3, 'class_type']='us_forest_service'
growth_2008.at[9, 'class_type']='other_federal'
growth_2008.at[13, 'class_type']='state_and_local_gov'
growth_2008.at[16, 'class_type']='nonindustrial_private'
growth_2008.at[17, 'class_type']='total_land'
growth_2008 = growth_2008.set_index('class_type')
growth_2008 = growth_2008.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
growth_2008['land_type'] = ['timberland', 'forest land']
growth_2008['year'] = '2008'

######

# 2007
growth_2007 = dict_trees2007.get('Tab 24')
growth_2007.columns = ['class_type', 'timberland', 'forest_land']
growth_2007 = growth_2007.head(21)
growth_2007 = growth_2007.tail(19)
growth_2007 = growth_2007.reset_index(drop=True)

growth_2007.at[3, 'class_type']='us_forest_service'
growth_2007.at[9, 'class_type']='other_federal'
growth_2007.at[14, 'class_type']='state_and_local_gov'
growth_2007.at[17, 'class_type']='nonindustrial_private'
growth_2007.at[18, 'class_type']='total_land'
growth_2007 = growth_2007.set_index('class_type')
growth_2007 = growth_2007.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
growth_2007['land_type'] = ['timberland', 'forest land']
growth_2007['year'] = '2007'

# combining all tables
growth = pd.concat([growth_2007, growth_2008, growth_2009, growth_2010, growth_2011, growth_2012, growth_2013, growth_2014, growth_2015, growth_2016])
growth = growth.reset_index(drop=True)
growth = growth[['year', 'land_type', 'us_forest_service', 'other_federal', 'state_and_local_gov', 'forest_industry', 'nonindustrial_private', 'total_land']]

# changing data type to numeric
growth.us_forest_service = pd.to_numeric(growth.us_forest_service)
growth.other_federal = pd.to_numeric(growth.other_federal)
growth.state_and_local_gov = pd.to_numeric(growth.state_and_local_gov)
growth.forest_industry = pd.to_numeric(growth.forest_industry)
growth.nonindustrial_private = pd.to_numeric(growth.nonindustrial_private)
growth.total_land = pd.to_numeric(growth.total_land)

# adding perc columns
growth['perc_us_forest_service'] = round(growth.us_forest_service/growth.total_land*100,2)
growth['perc_other_federal'] = round(growth.other_federal/growth.total_land*100,2)
growth['perc_state_and_local_gov'] = round(growth.state_and_local_gov/growth.total_land*100,2)
growth['perc_forest_industry'] = round(growth.forest_industry/growth.total_land*100,2)
growth['perc_nonindustrial_private'] = round(growth.nonindustrial_private/growth.total_land*100,2)

# fixing format
growth_sub = pd.melt(growth, id_vars=['year', 'land_type'], value_vars=['us_forest_service', 'other_federal', 'state_and_local_gov', 'forest_industry', 'nonindustrial_private', 'total_land'])
growth_sub.columns = ['year', 'land_type', 'class_type', 'million_cubic_ft']
growth_perc = growth.drop(columns=['us_forest_service', 'other_federal', 'state_and_local_gov', 'forest_industry', 'nonindustrial_private', 'total_land'])
growth_perc.columns = ['year', 'land_type', 'us_forest_service', 'other_federal', 'state_and_local_gov', 'forest_industry', 'nonindustrial_private']
growth_perc = pd.melt(growth_perc, id_vars=['year', 'land_type'], value_vars=['us_forest_service', 'other_federal', 'state_and_local_gov', 'forest_industry', 'nonindustrial_private'])
growth_perc.columns = ['year', 'land_type', 'class_type', 'perc_total_land']
growth = pd.merge(growth_sub, growth_perc, on=['year', 'land_type', 'class_type'], how='outer')
growth

     year    land_type         class_type  million_cubic_ft  perc_total_land
0    2007   timberland  us_forest_service              26.6             3.46
1    2007  forest land  us_forest_service              29.2             3.73
2    2008   timberland  us_forest_service              23.9             3.13
3    2008  forest land  us_forest_service              26.2             3.38
4    2009   timberland  us_forest_service              22.4             2.93
..    ...          ...                ...               ...              ...
115  2014  forest land         total_land             701.3              NaN
116  2015   timberland         total_land             734.9              NaN
117  2015  forest land         total_land             746.4              NaN
118  2016   timberland         total_land             788.4              NaN
119  2016  forest land         total_land             799.7              NaN

[120 rows x 5 columns]

In [8]:
## Table 32
## Land by Net Removal of Trees, in million cubic feet

# 2016
removal_2016 = dict_trees2016.get('Tab 32')
removal_2016.columns = ['class_type', 'timberland', 'forest_land']
removal_2016 = removal_2016.head(24)
removal_2016 = removal_2016.tail(22)
removal_2016 = removal_2016.reset_index(drop=True)

removal_2016.at[2, 'class_type']='us_forest_service'
removal_2016.at[6, 'class_type']='other_federal'
removal_2016.at[10, 'class_type']='state_and_local_gov'
removal_2016.at[14, 'class_type']='forest_industry'
removal_2016.at[20, 'class_type']='nonindustrial_private'
removal_2016.at[21, 'class_type']='total_land'
removal_2016 = removal_2016.set_index('class_type')
removal_2016 = removal_2016.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'forest_industry', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
removal_2016['land_type'] = ['timberland', 'forest land']
removal_2016['year'] = '2016'

######

# 2015
removal_2015 = dict_trees2015.get('Tab 32')
removal_2015.columns = ['class_type', 'timberland', 'forest_land']
removal_2015 = removal_2015.head(17)
removal_2015 = removal_2015.tail(15)
removal_2015 = removal_2015.reset_index(drop=True)

removal_2015.at[2, 'class_type']='us_forest_service'
removal_2015.at[6, 'class_type']='other_federal'
removal_2015.at[10, 'class_type']='state_and_local_gov'
removal_2015.at[13, 'class_type']='nonindustrial_private'
removal_2015.at[14, 'class_type']='total_land'
removal_2015 = removal_2015.set_index('class_type')
removal_2015 = removal_2015.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
removal_2015['land_type'] = ['timberland', 'forest land']
removal_2015['year'] = '2015'

######

# 2014
removal_2014 = dict_trees2014.get('Tab 32')
removal_2014.columns = ['class_type', 'timberland', 'forest_land']
removal_2014 = removal_2014.head(15)
removal_2014 = removal_2014.tail(13)
removal_2014 = removal_2014.reset_index(drop=True)

removal_2014.at[4, 'class_type']='other_federal'
removal_2014.at[8, 'class_type']='state_and_local_gov'
removal_2014.at[11, 'class_type']='nonindustrial_private'
removal_2014.at[12, 'class_type']='total_land'
removal_2014 = removal_2014.set_index('class_type')
removal_2014 = removal_2014.transpose()[['other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
removal_2014['land_type'] = ['timberland', 'forest land']
removal_2014['year'] = '2014'

######

# 2013
removal_2013 = dict_trees2013.get('Tab 32')
removal_2013.columns = ['class_type', 'timberland', 'forest_land']
removal_2013 = removal_2013.head(18)
removal_2013 = removal_2013.tail(16)
removal_2013 = removal_2013.reset_index(drop=True)

removal_2013.at[2, 'class_type']='us_forest_service'
removal_2013.at[7, 'class_type']='other_federal'
removal_2013.at[11, 'class_type']='state_and_local_gov'
removal_2013.at[14, 'class_type']='nonindustrial_private'
removal_2013.at[15, 'class_type']='total_land'
removal_2013 = removal_2013.set_index('class_type')
removal_2013 = removal_2013.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
removal_2013['land_type'] = ['timberland', 'forest land']
removal_2013['year'] = '2013'

######

# 2012
removal_2012 = dict_trees2012.get('Tab 32')
removal_2012.columns = ['class_type', 'timberland', 'forest_land']
removal_2012 = removal_2012.head(18)
removal_2012 = removal_2012.tail(16)
removal_2012 = removal_2012.reset_index(drop=True)

removal_2012.at[2, 'class_type']='us_forest_service'
removal_2012.at[7, 'class_type']='other_federal'
removal_2012.at[11, 'class_type']='state_and_local_gov'
removal_2012.at[14, 'class_type']='nonindustrial_private'
removal_2012.at[15, 'class_type']='total_land'
removal_2012 = removal_2012.set_index('class_type')
removal_2012 = removal_2012.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
removal_2012['land_type'] = ['timberland', 'forest land']
removal_2012['year'] = '2012'

######

# 2011
removal_2011 = dict_trees2011.get('Tab 32')
removal_2011.columns = ['class_type', 'timberland', 'forest_land']
removal_2011 = removal_2011.head(18)
removal_2011 = removal_2011.tail(16)
removal_2011 = removal_2011.reset_index(drop=True)

removal_2011.at[2, 'class_type']='us_forest_service'
removal_2011.at[7, 'class_type']='other_federal'
removal_2011.at[11, 'class_type']='state_and_local_gov'
removal_2011.at[14, 'class_type']='nonindustrial_private'
removal_2011.at[15, 'class_type']='total_land'
removal_2011 = removal_2011.set_index('class_type')
removal_2011 = removal_2011.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
removal_2011['land_type'] = ['timberland', 'forest land']
removal_2011['year'] = '2011'

######

# 2010
removal_2010 = dict_trees2010.get('Tab 32')
removal_2010.columns = ['class_type', 'timberland', 'forest_land']
removal_2010 = removal_2010.head(18)
removal_2010 = removal_2010.tail(16)
removal_2010 = removal_2010.reset_index(drop=True)

removal_2010.at[2, 'class_type']='us_forest_service'
removal_2010.at[7, 'class_type']='other_federal'
removal_2010.at[11, 'class_type']='state_and_local_gov'
removal_2010.at[14, 'class_type']='nonindustrial_private'
removal_2010.at[15, 'class_type']='total_land'
removal_2010 = removal_2010.set_index('class_type')
removal_2010 = removal_2010.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
removal_2010['land_type'] = ['timberland', 'forest land']
removal_2010['year'] = '2010'

######

# 2009
removal_2009 = dict_trees2009.get('Tab 32')
removal_2009.columns = ['class_type', 'timberland', 'forest_land']
removal_2009 = removal_2009.head(17)
removal_2009 = removal_2009.tail(15)
removal_2009 = removal_2009.reset_index(drop=True)

removal_2009.at[2, 'class_type']='us_forest_service'
removal_2009.at[6, 'class_type']='other_federal'
removal_2009.at[10, 'class_type']='state_and_local_gov'
removal_2009.at[13, 'class_type']='nonindustrial_private'
removal_2009.at[14, 'class_type']='total_land'
removal_2009 = removal_2009.set_index('class_type')
removal_2009 = removal_2009.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
removal_2009['land_type'] = ['timberland', 'forest land']
removal_2009['year'] = '2009'

######

# 2008
removal_2008 = dict_trees2008.get('Tab 32')
removal_2008.columns = ['class_type', 'timberland', 'forest_land']
removal_2008 = removal_2008.head(17)
removal_2008 = removal_2008.tail(15)
removal_2008 = removal_2008.reset_index(drop=True)

removal_2008.at[2, 'class_type']='us_forest_service'
removal_2008.at[6, 'class_type']='other_federal'
removal_2008.at[10, 'class_type']='state_and_local_gov'
removal_2008.at[13, 'class_type']='nonindustrial_private'
removal_2008.at[14, 'class_type']='total_land'
removal_2008 = removal_2008.set_index('class_type')
removal_2008 = removal_2008.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
removal_2008['land_type'] = ['timberland', 'forest land']
removal_2008['year'] = '2008'

######

# 2007
removal_2007 = dict_trees2007.get('Tab 32')
removal_2007.columns = ['class_type', 'timberland', 'forest_land']
removal_2007 = removal_2007.head(18)
removal_2007 = removal_2007.tail(16)
removal_2007 = removal_2007.reset_index(drop=True)

removal_2007.at[2, 'class_type']='us_forest_service'
removal_2007.at[6, 'class_type']='other_federal'
removal_2007.at[11, 'class_type']='state_and_local_gov'
removal_2007.at[14, 'class_type']='nonindustrial_private'
removal_2007.at[15, 'class_type']='total_land'
removal_2007 = removal_2007.set_index('class_type')
removal_2007 = removal_2007.transpose()[['us_forest_service', 'other_federal', 'state_and_local_gov', 'nonindustrial_private', 'total_land']].reset_index(drop=True)
removal_2007['land_type'] = ['timberland', 'forest land']
removal_2007['year'] = '2007'

# combining all tables
removal = pd.concat([removal_2007, removal_2008, removal_2009, removal_2010, removal_2011, removal_2012, removal_2013, removal_2014, removal_2015, removal_2016])
removal = removal.reset_index(drop=True)
removal = removal[['year', 'land_type', 'us_forest_service', 'other_federal', 'state_and_local_gov', 'forest_industry', 'nonindustrial_private', 'total_land']]

# changing data type to numeric
removal.us_forest_service = pd.to_numeric(removal.us_forest_service)
removal.other_federal = pd.to_numeric(removal.other_federal)
removal.state_and_local_gov = pd.to_numeric(removal.state_and_local_gov)
removal.forest_industry = pd.to_numeric(removal.forest_industry)
removal.nonindustrial_private = pd.to_numeric(removal.nonindustrial_private)
removal.total_land = pd.to_numeric(removal.total_land)

# adding perc columns
removal['perc_us_forest_service'] = round(removal.us_forest_service/removal.total_land*100,2)
removal['perc_other_federal'] = round(removal.other_federal/removal.total_land*100,2)
removal['perc_state_and_local_gov'] = round(removal.state_and_local_gov/removal.total_land*100,2)
removal['perc_forest_industry'] = round(removal.forest_industry/removal.total_land*100,2)
removal['perc_nonindustrial_private'] = round(removal.nonindustrial_private/removal.total_land*100,2)

# fixing format
removal_sub = pd.melt(removal, id_vars=['year', 'land_type'], value_vars=['us_forest_service', 'other_federal', 'state_and_local_gov', 'forest_industry', 'nonindustrial_private', 'total_land'])
removal_sub.columns = ['year', 'land_type', 'class_type', 'million_cubic_ft']
removal_perc = removal.drop(columns=['us_forest_service', 'other_federal', 'state_and_local_gov', 'forest_industry', 'nonindustrial_private', 'total_land'])
removal_perc.columns = ['year', 'land_type', 'us_forest_service', 'other_federal', 'state_and_local_gov', 'forest_industry', 'nonindustrial_private']
removal_perc = pd.melt(removal_perc, id_vars=['year', 'land_type'], value_vars=['us_forest_service', 'other_federal', 'state_and_local_gov', 'forest_industry', 'nonindustrial_private'])
removal_perc.columns = ['year', 'land_type', 'class_type', 'perc_total_land']
removal = pd.merge(removal_sub, removal_perc, on=['year', 'land_type', 'class_type'], how='outer')
removal

     year    land_type         class_type  million_cubic_ft  perc_total_land
0    2007   timberland  us_forest_service               1.7             0.41
1    2007  forest land  us_forest_service               1.7             0.41
2    2008   timberland  us_forest_service               2.0             0.45
3    2008  forest land  us_forest_service               1.8             0.41
4    2009   timberland  us_forest_service               2.8             0.60
..    ...          ...                ...               ...              ...
115  2014  forest land         total_land             408.7              NaN
116  2015   timberland         total_land             389.1              NaN
117  2015  forest land         total_land             385.7              NaN
118  2016   timberland         total_land             373.3              NaN
119  2016  forest land         total_land             369.5              NaN

[120 rows x 5 columns]

In [9]:
# exporting all tables into csv
ownership_class.to_csv('trees_ownership_class.csv')
disturbed.to_csv('trees_disturbed.csv')
volume.to_csv('trees_volume.csv')
growth.to_csv('trees_growth.csv')
removal.to_csv('trees_removal.csv')
species.to_csv('trees_species.csv')